import { expect, it, vi } from 'vitest';
import { executeCurrentAccountLink } from './friends-account-link-action.js';
function fixture(){let current=true;const opts={accountId:'a',personId:'p',isCurrent:()=>current,readAccount:vi.fn(async()=>({id:'a'} as any)),readPerson:vi.fn(async()=>({id:'p'} as any)),assign:vi.fn(async()=>{}),onApplied:vi.fn()};return {opts,replace:()=>{current=false;}};}
function deferred(){let resolve!:(value:any)=>void;const promise=new Promise<any>(a=>resolve=a);return {promise,resolve};}
it('links the exact current native rows once and admits current completion',async()=>{const f=fixture();await executeCurrentAccountLink(f.opts);expect(f.opts.assign).toHaveBeenCalledExactlyOnceWith('a','p');expect(f.opts.onApplied).toHaveBeenCalledOnce();});
it('rejects a captured action before reads and assignment',async()=>{const f=fixture();f.replace();await executeCurrentAccountLink(f.opts);expect(f.opts.readAccount).not.toHaveBeenCalled();expect(f.opts.assign).not.toHaveBeenCalled();});
it('rejects replacement while native reads are pending',async()=>{const f=fixture(),pending=deferred();f.opts.readAccount.mockReturnValueOnce(pending.promise);const operation=executeCurrentAccountLink(f.opts);f.replace();pending.resolve({id:'a'});await operation;expect(f.opts.assign).not.toHaveBeenCalled();});
it('does not assign a removed or mismatched native identity',async()=>{const f=fixture();f.opts.readPerson.mockResolvedValueOnce({id:'other'} as any);await expect(executeCurrentAccountLink(f.opts)).rejects.toThrow('unavailable');expect(f.opts.assign).not.toHaveBeenCalled();});
it('allows an already-started assignment to settle but never moves obsolete selection',async()=>{const f=fixture(),pending=deferred();f.opts.assign.mockReturnValueOnce(pending.promise);const operation=executeCurrentAccountLink(f.opts);await Promise.resolve();await Promise.resolve();expect(f.opts.assign).toHaveBeenCalledOnce();f.replace();pending.resolve(undefined);await operation;expect(f.opts.onApplied).not.toHaveBeenCalled();});
