version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      development-tooling:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /packages/desktop/src-tauri
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
