// This file is generated by scripts/generate-library-core-contract.mjs.

pub const SQLITE_CONTRACT_VERSION: u32 = 1;
pub const SQLITE_SCHEMA_VERSION: u32 = 1;
pub const SQLITE_PROTOCOL_VERSION: u32 = 2;
pub const NORMALIZED_CHECKPOINT_FORMAT: &str = "freed_normalized_checkpoint_v2";
pub const CHECKPOINT_RECORD_MAXIMUM_CANONICAL_BYTES: usize = 131072;
pub const CHECKPOINT_PAGE_MAXIMUM_DECODED_BYTES: usize = 2097152;
pub const CHECKPOINT_PAGE_MAXIMUM_RECORDS: usize = 128;
pub const NATIVE_EXPORT_MAXIMUM_RESPONSE_BYTES: usize = 1048576;
pub const CONTENT_CHUNK_BYTES: usize = 65536;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckpointRecordKind {
    CheckpointHeader,
    FeedItem,
    RssFeed,
    Person,
    Account,
    Preference,
    Relationship,
    FieldClock,
    Tombstone,
    ActorState,
    Receipt,
    BlobDescriptor,
    ContentChunk,
}

impl CheckpointRecordKind {
    pub const fn registry_key(self) -> &'static str {
        use CheckpointRecordKind::*;
        match self {
            CheckpointHeader => "00_checkpoint_header",
            FeedItem => "10_feed_item",
            RssFeed => "20_rss_feed",
            Person => "30_person",
            Account => "40_account",
            Preference => "50_preference",
            Relationship => "60_relationship",
            FieldClock => "70_field_clock",
            Tombstone => "80_tombstone",
            ActorState => "90_actor_state",
            Receipt => "a0_receipt",
            BlobDescriptor => "b0_blob_descriptor",
            ContentChunk => "b1_content_chunk",
        }
    }
}

pub const OPERATION_IDS: &[&str] = &[
    "account_person_assignment",
    "account_remove",
    "account_restore",
    "account_upsert",
    "feed_item_archive_assignment",
    "feed_item_capture_upsert",
    "feed_item_like_assignment",
    "feed_item_like_sync_receipt",
    "feed_item_read_assignment",
    "feed_item_remove",
    "feed_item_restore",
    "feed_item_saved_assignment",
    "feed_item_seen_sync_receipt",
    "feed_items_archive_frozen",
    "feed_items_archive_read_unsaved_frozen",
    "feed_items_content_signals_backfill_frozen",
    "feed_items_deduplicate_frozen",
    "feed_items_delete_archived_frozen",
    "feed_items_prune_archived_frozen",
    "feed_items_read_frozen",
    "feed_items_unarchive_saved_frozen",
    "person_reach_out_append",
    "person_remove_and_accounts",
    "person_remove_detach_accounts",
    "person_restore",
    "person_upsert",
    "preferences_leaf_assignment",
    "provider_capture_snapshot_reconcile",
    "provider_intent",
    "rss_feed_remove_keep_items",
    "rss_feed_remove_with_items",
    "rss_feed_restore",
    "rss_feed_title_assignment",
    "rss_feed_upsert",
    "rss_feeds_heal_untitled_frozen",
    "rss_feeds_remove_keep_items",
    "rss_feeds_remove_with_items",
    "sample_library_import",
    "sample_library_remove",
];

pub const QUERY_IDS: &[&str] = &[
    "account_detail_v1",
    "background_item_page_v1",
    "change_feed_v1",
    "content_fetch_claim_v1",
    "export_enumeration_v1",
    "feed_browse_page_v1",
    "feed_browse_page_v2",
    "feed_browse_page_v3",
    "feed_facets_v1",
    "feed_page_v1",
    "feed_subscription_page_v1",
    "item_detail_v1",
    "item_reader_body_v1",
    "library_facet_summary_v1",
    "library_surface_items_v1",
    "map_markers_v1",
    "person_detail_v1",
    "person_timeline_v1",
    "persons_graph_v1",
    "preferences_snapshot_v1",
    "provider_action_claim_v1",
    "provider_media_page_v1",
    "repair_work_claim_v1",
    "saved_analytics_v1",
    "saved_feed_page_v1",
    "search_page_v1",
    "semantic_classification_claim_v1",
    "story_wall_candidates_v1",
];
