/* This file is generated by scripts/generate-library-core-contract.mjs. */

export const LIBRARY_CORE_NATIVE_COMMAND_PROTOCOL_VERSION = 1 as const;
export const LIBRARY_CORE_NATIVE_COMMAND_MAXIMUM_FRAME_BYTES = 4194304 as const;
export const LIBRARY_CORE_SQLITE_APPLICATION_ID = 1179796804 as const;
export const LIBRARY_CORE_SQLITE_CONTRACT_VERSION = 1 as const;
export const LIBRARY_CORE_SQLITE_SCHEMA_VERSION = 1 as const;
export const LIBRARY_CORE_SQLITE_PROTOCOL_VERSION = 2 as const;
export const LIBRARY_CORE_NORMALIZED_SCHEMA_SHA256 = "dd55a84d31d35f87210b4fe66a73d86ae5ec9c95e2539fcc679566fe2cc595ca" as const;
export const LIBRARY_CORE_NATIVE_COMMAND_IDS = [
  "append_checkpoint_stage_v2",
  "begin_checkpoint_stage_v2",
  "content_eviction_candidates_page_v1",
  "content_hydration_candidates_page_v1",
  "content_policy_set_v1",
  "content_state_get_v1",
  "describe_checkpoint_export_v2",
  "export_checkpoint_page_v2",
  "finalize_checkpoint_stage_v2",
  "inspect_storage_v1",
  "query_v1",
] as const;
export type LibraryCoreNativeCommandId = (typeof LIBRARY_CORE_NATIVE_COMMAND_IDS)[number];
