import type { SampleCharacterEpisode } from "./sample-character-arcs.js";

/** Exact image review and editorial admission are recorded in DEMO-CORPUS-500-ADMISSION.md. */
export const FIVE_HUNDRED_EPISODES_BY_CHARACTER: Readonly<
  Record<string, readonly SampleCharacterEpisode[]>
> = {
  "nudi-branch-manager": [
    {
      subject: "nudibranch underwater",
      mediaSha1: "132c45ae85dc04fbd3f381cd972135af36b1f7ea",
      classification: "conversation",
      theme: "social",
      title: "The orange one stayed",
      body: "The orange one climbed onto my back and waved every branch it had. I waited for a request. Apparently that was the request.",
    },
    {
      subject: "nudibranch underwater",
      mediaSha1: "999b6de9c270b6cf084e91d32519aab2f1b24366",
      classification: "inspiring",
      theme: "movement",
      title: "One ripple at a time",
      body: "The reef rose in ridges under my foot. I crossed each one with my whole body. By sunset I had traveled farther than the fish believed and less far than the rock noticed.",
    },
    {
      subject: "nudibranch underwater",
      mediaSha1: "f78edbd368573323bec2926ac2459c1cc009a6f6",
      classification: "personal",
      theme: "wonder",
      title: "Too much outfit",
      body: "I found a quiet patch of reef and arrived wearing every color I own. The quiet patch has adjusted its expectations.",
    },
    {
      subject: "nudibranch underwater",
      mediaSha1: "a1bfc86887366dde276f85612da527a42f49d3a1",
      classification: "news",
      theme: "wonder",
      title: "Wreck inspection",
      body: "The wreck has acquired sponge, anemones, and me. I inspected the new management. It is mostly attached and doing fine.",
    },
    {
      subject: "nudibranch underwater",
      mediaSha1: "6da2fa0f46144ea10d89649891e6e7aef2964355",
      classification: "conversation",
      theme: "social",
      title: "Yellow was not subtle",
      body: "A fish asked whether the yellow meant danger. I said yes. It came closer to see what kind.",
    },
    {
      subject: "nudibranch mating",
      mediaSha1: "eb7bef6396d1945ec5a0857133df9d4823a05a46",
      classification: "personal",
      theme: "courtship",
      title: "Meeting in the middle",
      body: "We both followed the same curve until there was nowhere left to pretend we were passing. It was an excellent piece of reef planning.",
    },
    {
      subject: "nudibranch mating",
      mediaSha1: "73f968222b4586886aea0bffbb604d025145f7af",
      classification: "personal",
      theme: "courtship",
      title: "Night appointment",
      body: "The sand was empty except for us. We approached slowly, which is also how we approach quickly, and neither of us arrived late.",
    },
    {
      subject: "nudibranch mating",
      mediaSha1: "abc0014a40d449c5440a942e67f25fe8eb77db5f",
      classification: "conversation",
      theme: "courtship",
      title: "The branch between us",
      body: "A thin branch kept touching both our faces. We moved around it from opposite sides and discovered we had solved the wrong separation.",
    },
    {
      subject: "nudibranch mating",
      mediaSha1: "ee89ea18638f7c2d68107f9680ee8279e6e6add7",
      classification: "personal",
      theme: "courtship",
      title: "Still the same meeting",
      body: "We separated by the width of a frill, then curled back together. Neither of us had finished leaving.",
    },
    {
      subject: "nudibranch mating",
      mediaSha1: "a9823dddb65fbaa1544f437e329ee064de5e86a2",
      classification: "inspiring",
      theme: "courtship",
      title: "Violet agreement",
      body: "We met in a blaze of violet and orange. For once, looking impossible made the introduction easier.",
    },
  ],
  "alma-eight": [
    {
      subject: "octopus underwater",
      mediaSha1: "065e78305e43fad164b1b2a8554f7c3aac81b477",
      classification: "personal",
      theme: "wonder",
      title: "The shell suited me",
      body: "I found two shells and tried the space between them. Six arms fit. The other two spent the afternoon insisting this counted as storage.",
    },
    {
      subject: "octopus underwater",
      mediaSha1: "478abcf6f074d529c2397e1acbc25f8f9bbf6139",
      classification: "event",
      theme: "movement",
      title: "Across the open sand",
      body: "Crossed the sand with nowhere to hide. I carried a dark cloud over my skin until the next rock agreed to be a room.",
    },
    {
      subject: "octopus underwater",
      mediaSha1: "1a5eb8dc89ba848835343bb24c303fede8f0bf0c",
      classification: "personal",
      theme: "wonder",
      title: "One arm checked",
      body: "I tucked seven arms into the hollow. The eighth went back out to check the view. It has always considered itself the sensible one.",
    },
    {
      subject: "octopus underwater",
      mediaSha1: "9f3e803cb343f6226d9d99a51865236795ef5a11",
      classification: "event",
      theme: "movement",
      title: "Sand with no opinion",
      body: "I crossed a pale patch where every step showed. Nothing chased me. I was almost disappointed by how responsibly the sand behaved.",
    },
    {
      subject: "octopus underwater",
      mediaSha1: "bb5870d5fe0f1204af04862a8f27bff790aaa21a",
      classification: "conversation",
      theme: "social",
      title: "The reef answered twice",
      body: "A diver pointed at the reef. I raised one eye from the reef. He pointed harder. I changed color and let him discover me twice.",
    },
  ],
  "rhea-return": [
    {
      subject: "sea turtle underwater",
      mediaSha1: "796e07c8971cc82e3b63a17287d8b6222a88052d",
      classification: "inspiring",
      theme: "movement",
      title: "Room beneath the surface",
      body: "The water held my whole weight and asked only that I keep moving. I stretched one flipper into the blue and the rest of me followed.",
    },
    {
      subject: "sea turtle underwater",
      mediaSha1: "815f8035263d22aed8234c8e059a616566a51b7d",
      classification: "personal",
      theme: "feeding",
      title: "The reef was lunch",
      body: "I chose one bite from the reef. It came with three smaller things and a piece that would not come loose. I kept the original decision.",
    },
    {
      subject: "sea turtle underwater",
      mediaSha1: "58113c4024c70176356feacb77ce09759f932a53",
      classification: "event",
      theme: "movement",
      title: "One breath above",
      body: "I rose through the brightening water, took one breath, and turned down again. The whole sky was useful for less than a second.",
    },
    {
      subject: "sea turtle underwater",
      mediaSha1: "07d2d0f0f4fac6beae66f49e818aa34a4d42fb72",
      classification: "personal",
      theme: "wonder",
      title: "Close enough to look",
      body: "I came near the glass and found another sea beyond it, full of faces that could not swim over. We watched each other fail to cross.",
    },
    {
      subject: "sea turtle underwater",
      mediaSha1: "28a5f1e2ebc0aa10bc62c5477e74b24c6f3970de",
      classification: "inspiring",
      theme: "movement",
      title: "Past the last coral",
      body: "The reef ended and open water began. I kept the old direction until the new emptiness became a route.",
    },
  ],
  "iris-undertow": [
    {
      subject: "cuttlefish underwater",
      mediaSha1: "3a38be9c82ebe3c893e15462801776eb2d238fa2",
      classification: "personal",
      theme: "wonder",
      title: "Color before courage",
      body: "My skin announced every thought before I chose one. I crossed the rock anyway, changing my mind in public.",
    },
    {
      subject: "cuttlefish underwater",
      mediaSha1: "cf173b28df745cc6f95a9cc1e86a76452352c0c1",
      classification: "event",
      theme: "danger",
      title: "Dark all at once",
      body: "A shadow passed and I became the dark rock beneath me. The shadow left. My skin took longer to believe it.",
    },
    {
      subject: "cuttlefish underwater",
      mediaSha1: "6e3676c71296ab888b151ca04dd0354101ef38f1",
      classification: "conversation",
      theme: "social",
      title: "A broad reply",
      body: "He widened his arms and sent stripes over his back. I widened mine. We had nothing further to say and continued saying it.",
    },
    {
      subject: "cuttlefish underwater",
      mediaSha1: "2d8ff1d2ebdb969a7dbc6c3feb6b09cafde9144e",
      classification: "inspiring",
      theme: "movement",
      title: "The edge kept moving",
      body: "Light rippled across the sand and across me. I stopped trying to match one patch and moved with the change.",
    },
    {
      subject: "cuttlefish underwater",
      mediaSha1: "42e319023bd2878ee25eebd7e1be783e101d3db2",
      classification: "personal",
      theme: "wonder",
      title: "Copper for no reason",
      body: "Nothing threatened me. Nothing courted me. I turned copper in the clear water because the color arrived and there was room for it.",
    },
  ],
  "mora-grey": [
    {
      subject: "moray eel underwater",
      mediaSha1: "d1b1432ee2a7b12331cb43750c530353459bc984",
      classification: "personal",
      theme: "wonder",
      title: "The view from here",
      body: "Put my head outside and left the rest in the dark. The reef was busy enough for that amount of me.",
    },
    {
      subject: "moray eel underwater",
      mediaSha1: "4cd1a3142d0da6628a5e55bec0a22bb7ad9ba15e",
      classification: "conversation",
      theme: "social",
      title: "Mouth open, listening",
      body: "The little fish waited for me to close my mouth before speaking. We may be here for some time.",
    },
    {
      subject: "moray eel underwater",
      mediaSha1: "9a40fb808743a382cf4b04e1420d9b0cef2bc94a",
      classification: "event",
      theme: "movement",
      title: "More eel than doorway",
      body: "The opening looked generous from outside. Halfway in, I discovered the opening had been judging only my face.",
    },
    {
      subject: "moray eel underwater",
      mediaSha1: "0398320ee4eb465328beac1131eb2a079e3a6e53",
      classification: "personal",
      theme: "wonder",
      title: "Gold at the entrance",
      body: "Sunlight reached the lip of my hole and found the spots on my face. I stayed there until the light moved on without the rest of me.",
    },
    {
      subject: "moray eel underwater",
      mediaSha1: "043461bd82765ecd984fde35980fe0efea3b3ac3",
      classification: "conversation",
      theme: "social",
      title: "The neighbor above",
      body: "Another head appeared over mine. We both opened our mouths to make room for breathing and looked, briefly, like a very bad idea.",
    },
  ],
  "frogbert-angler": [
    {
      subject: "frogfish underwater",
      mediaSha1: "ab98dabf54fe33be92581795707d73fd56b68176",
      classification: "conversation",
      theme: "wonder",
      title: "Found, unfortunately",
      body: "the diver looked straight at me three times. on the fourth I looked back. apparently camouflage includes customer service now.",
    },
    {
      subject: "frogfish underwater",
      mediaSha1: "d8db811f9a3957e75569f46ac91be3a8456373b0",
      classification: "personal",
      theme: "movement",
      title: "Pink takes effort",
      body: "walked across brown sand wearing pink. there was nowhere for the color to hide so I carried it myself.",
    },
    {
      subject: "frogfish underwater",
      mediaSha1: "28f071a8ba9eb3e27a92f099918b66dabe6f8662",
      classification: "conversation",
      theme: "social",
      title: "Open for questions",
      body: "opened my mouth. everybody left. this is why I prefer statements.",
    },
    {
      subject: "frogfish underwater",
      mediaSha1: "01e2e869995438145c0354c19e554df0a82dffd3",
      classification: "event",
      theme: "feeding",
      title: "Lure went first",
      body: "sent the lure round the corner before my face. it came back without lunch and with no explanation.",
    },
    {
      subject: "frogfish underwater",
      mediaSha1: "e710824197892596f5f929fb93529038436cc68d",
      classification: "personal",
      theme: "wonder",
      title: "White with orange bits",
      body: "sat on black sand looking like a dropped celebration. nothing ate me. tasteful design remains undefeated.",
    },
  ],
  "ada-spine": [
    {
      subject: "starfish underwater",
      mediaSha1: "7f5994ab6c0ee35f2f3050ef3c8c4921e1c00303",
      classification: "personal",
      theme: "movement",
      title: "All the arms disagreed",
      body: "Every branch found a different current. I moved in all directions and arrived exactly where I began, only more thoroughly.",
    },
    {
      subject: "starfish underwater",
      mediaSha1: "bdaab2668a85d30e885c3dedb8c6ed40645b782c",
      classification: "news",
      theme: "feeding",
      title: "Coral report",
      body: "Reached the next coral and began eating. The reef would like this described as an emergency. I would like it described as lunch.",
    },
    {
      subject: "starfish underwater",
      mediaSha1: "271c99e5ae211b5068c30d8c842ad4682dee3241",
      classification: "event",
      theme: "movement",
      title: "Spines through the gap",
      body: "The gap was wide enough for an arm and then another. By the time my middle arrived, the gap had developed objections.",
    },
    {
      subject: "starfish underwater",
      mediaSha1: "76a48ac598777a70e84de7466014cb323f43e8c1",
      classification: "personal",
      theme: "wonder",
      title: "Blue was underneath",
      body: "The light shifted and blue appeared between my spines. I had been carrying a better color where I could not see it.",
    },
    {
      subject: "starfish underwater",
      mediaSha1: "c78c6cfa7dfba54e02b07bcf4b72505790096c56",
      classification: "inspiring",
      theme: "movement",
      title: "Five directions forward",
      body: "I chose a direction with one arm. The other four came along without admitting it was a good choice.",
    },
  ],
  "mina-tangle": [
    {
      subject: "feather star underwater",
      mediaSha1: "c770061038bc07a93da4549ae463b9f22c737740",
      classification: "personal",
      theme: "wonder",
      title: "She opened above me",
      body: "She opened every arm into the current. I stayed underneath and called it shelter. She called it lunch.",
    },
    {
      subject: "feather star underwater",
      mediaSha1: "b8d51c34b772f25b771ea6c26bc19da8d9eb1e4f",
      classification: "event",
      theme: "weather",
      title: "Night made more arms",
      body: "At dusk she unfolded until the rock disappeared beneath her. I held on to the part that remained certain.",
    },
    {
      subject: "feather star underwater",
      mediaSha1: "5a67fefad83a2b46a32a05011205a39359abaf0d",
      classification: "conversation",
      theme: "social",
      title: "A crowded handrail",
      body: "Another small crab took the next arm. We nodded. The feather star moved, and we both pretended we had chosen to meet closer.",
    },
    {
      subject: "feather star underwater",
      mediaSha1: "54535127c9d580838bebb184994715d5017e9752",
      classification: "inspiring",
      theme: "movement",
      title: "Red against the reef",
      body: "She opened red arms over broken coral. I had thought shelter should disappear into its surroundings. She had other standards.",
    },
    {
      subject: "feather star underwater",
      mediaSha1: "0ee0aa1cd9a898bbeeeb1c67120d009a5bd829a8",
      classification: "personal",
      theme: "movement",
      title: "The last curled arm",
      body: "She folded arm after arm for daylight. I moved inward each time. By the last curl, I was holding the only place left.",
    },
  ],
  "manny-tis": [
    {
      subject: "praying mantis",
      mediaSha1: "27b7ebe285129ff07853aa2d19185414fffd682c",
      classification: "event",
      theme: "feeding",
      title: "Lunch required both hands",
      body: "The bee objected with every part of itself. I held on with both forelegs and tried to look as though lunch usually needed this much supervision.",
    },
    {
      subject: "praying mantis",
      mediaSha1: "c88ce5d5c8cd990996d841db9af09646ae2d47c7",
      classification: "personal",
      theme: "wonder",
      title: "Portrait with antennae",
      body: "I turned toward the light. One antenna remained interested in somewhere else. I have published the more decisive half of the pose.",
    },
    {
      subject: "praying mantis",
      mediaSha1: "d419335f51a0e926dbd6a7a49d0e5449b6790d0a",
      classification: "conversation",
      theme: "social",
      title: "The branch had notes",
      body: "I stepped onto the branch and it bent. I stepped back. It rose. We repeated this until I accepted that the branch was participating.",
    },
    {
      subject: "praying mantis",
      mediaSha1: "e5f6a877347285e1ca1e38f040566752f1b90305",
      classification: "inspiring",
      theme: "danger",
      title: "Green enough to stay",
      body: "The leaves moved in the wind and I moved with them. For once, fear and excellent posture required the same thing.",
    },
    {
      subject: "praying mantis",
      mediaSha1: "5e6da761a344b8f0a359091ac1b995a6d5c4056e",
      classification: "event",
      theme: "movement",
      title: "Across one red leaf",
      body: "The red leaf made no attempt to match me. I crossed it quickly and became, for several steps, the most obvious thing alive.",
    },
  ],
  "luna-after": [
    {
      subject: "moth macro",
      mediaSha1: "7b4cc68b8a0766d8fc393b980b0392fb51fa1a07",
      classification: "event",
      theme: "feeding",
      title: "Hovering was the meal",
      body: "I drank without landing. The flower kept moving under me, so I moved too. We made eating look like an argument with air.",
    },
    {
      subject: "moth macro",
      mediaSha1: "d6ddc71b5b2fe134b23e8029a374419d2e095c63",
      classification: "personal",
      theme: "wonder",
      title: "Metal in the wings",
      body: "The sun found colors my wings had kept folded. I opened them wider. Having no mouth does leave more time for vanity.",
    },
    {
      subject: "moth macro",
      mediaSha1: "a2c5576cde66ffd0acaca8bb9b0bd632660e0d47",
      classification: "conversation",
      theme: "social",
      title: "The flower was occupied",
      body: "I landed beside a beetle already eating. It shifted one foot. I shifted one foot. The flower carried both our compromise.",
    },
    {
      subject: "moth macro",
      mediaSha1: "a2ff00df4e6880894c2b8feed9c67aaeb91a8eb6",
      classification: "event",
      theme: "weather",
      title: "Under the leaf edge",
      body: "Rain struck the upper leaf and reached me as trembling. I stayed beneath it until the whole green roof stopped speaking.",
    },
    {
      subject: "moth macro",
      mediaSha1: "a66450a86a603b0991f35e4ceadd7e8616a82eb4",
      classification: "inspiring",
      theme: "transformation",
      title: "The pattern arrived whole",
      body: "I opened wings I had never used and found a finished pattern on both. Childhood had been doing more than eating.",
    },
  ],
  "ottilie-hook": [
    {
      subject: "weevil macro",
      mediaSha1: "11aff9ac790294975d7a6ed0f9ed80f77f2d9c39",
      classification: "personal",
      theme: "wonder",
      title: "Profile of the problem",
      body: "They photographed my long snout from the side. It is the first image that admits how early I arrive at things.",
    },
    {
      subject: "weevil macro",
      mediaSha1: "ac774a69b9abc6c6308fcbe139f2123309110dec",
      classification: "news",
      theme: "wonder",
      title: "Inspection from above",
      body: "New view from above confirms that the snout is attached to the rest of me. Several acorns had raised questions.",
    },
    {
      subject: "weevil macro",
      mediaSha1: "c039112c7d6faa3bb68b784136ed5db77027ec4c",
      classification: "event",
      theme: "movement",
      title: "Green on brown",
      body: "Crossed dark soil in a green coat. Every step was visible. I took smaller steps, which only extended the exhibition.",
    },
    {
      subject: "weevil macro",
      mediaSha1: "1157a22d4d1197d25fa4450546954b171da1cfb4",
      classification: "conversation",
      theme: "social",
      title: "The finger arrived",
      body: "A finger appeared beside me. I put one foot on it to establish scale. The finger has misunderstood this as consent to travel.",
    },
    {
      subject: "weevil macro",
      mediaSha1: "9ded800b7ef66e2ff88b2699f0ba5aea3f8f489d",
      classification: "personal",
      theme: "movement",
      title: "Leaf edge negotiations",
      body: "Reached the leaf edge and leaned past it with my snout. The rest of me requested a more conventional crossing.",
    },
  ],
  "colm-still": [
    {
      subject: "basalt columns geology",
      mediaSha1: "3f9b693f781f823855e80670161956b11e7b2ffe",
      classification: "news",
      theme: "wonder",
      title: "Visible from the road",
      body: "The road arrived after I cooled. Travelers now stop to look at my cracks. None have yet improved them.",
    },
    {
      subject: "basalt columns geology",
      mediaSha1: "cb5112cc2c35a3b0d36ea52ec2dd618877c27c35",
      classification: "inspiring",
      theme: "transformation",
      title: "The wall became many",
      body: "Cooling pulled one mass into columns. We have stood apart together ever since.",
    },
    {
      subject: "basalt columns geology",
      mediaSha1: "14df3138e46e729b9e2eec190a94d60096d26ecd",
      classification: "personal",
      theme: "wonder",
      title: "Flowers in the fracture",
      body: "A flower rooted in the crack that separated us. I had called it damage for longer than the flower's entire ancestry.",
    },
    {
      subject: "basalt columns geology",
      mediaSha1: "39ec373c1a7beec5ac2e862b12e376156cdbb97d",
      classification: "event",
      theme: "weather",
      title: "Ice found every seam",
      body: "Snow settled along each crack. For a season, the lines made when I cooled were drawn again in white.",
    },
    {
      subject: "basalt columns geology",
      mediaSha1: "57339d13cbaba5b9453a0fa13aabc80f92a8e103",
      classification: "inspiring",
      theme: "wonder",
      title: "Leaning into the sea",
      body: "The cliff tilted and we columns kept our company. Even stone can fall slowly enough to look like standing.",
    },
  ],
  "nova-remains": [
    {
      subject: "supernova remnant NASA",
      mediaSha1: "315078d06ac86e674de56d66f859d89bc516295e",
      classification: "news",
      theme: "cosmic",
      title: "Kepler saw the light",
      body: "My light reached Earth in 1604 and became a new star in human records. The material itself kept expanding, late to its own announcement.",
    },
    {
      subject: "supernova remnant NASA",
      mediaSha1: "308e74d35484433631fb5f786294a1ecb6d6ae36",
      classification: "inspiring",
      theme: "cosmic",
      title: "A thousand years outward",
      body: "For a thousand years my shock has widened through space. The center is gone, but the edge still knows which way is outward.",
    },
    {
      subject: "supernova remnant NASA",
      mediaSha1: "69e0ef67759def985b27811707ef2b9baae03ce6",
      classification: "news",
      theme: "cosmic",
      title: "The shell came into view",
      body: "Radio and optical light traced a shell too faint for ordinary sight. I had not become invisible. The question had needed different eyes.",
    },
    {
      subject: "supernova remnant NASA",
      mediaSha1: "451c25be5d978d1393363812ca1ae2f31f2db618",
      classification: "news",
      theme: "cosmic",
      title: "Seen in X rays",
      body: "Hot gas drew one version of my remains in X rays. It is awkward to learn that ruin has layers and each instrument gets a different confession.",
    },
    {
      subject: "supernova remnant NASA",
      mediaSha1: "c03fc532fda31868f7f0269abd2fe2eaa4560fb9",
      classification: "inspiring",
      theme: "cosmic",
      title: "Visible light held on",
      body: "Visible light caught my thin filaments still crossing space. Delicate is not the opposite of violent. Sometimes it is what violence leaves moving.",
    },
  ],
  "orin-clear": [
    {
      subject: "comb jelly underwater",
      mediaSha1: "2dad028765a69dde01d239d395a67b13ac1c9923",
      classification: "personal",
      theme: "wonder",
      title: "Clear with moving colors",
      body: "Light ran in colors along my rows of cilia. I remained mostly clear and somehow became the loudest thing in the water.",
    },
  ],
  "flora-mingo": [
    {
      subject: "flamingo",
      mediaSha1: "edc8481461023dbcd11a9cdd43607db51b9a5e49",
      classification: "personal",
      theme: "transformation",
      title: "Pink is in progress",
      body: "My feathers are still grey. The adults stand around like finished conclusions. I have begun with the legs.",
    },
  ],
  "cygnus-shy": [
    {
      subject: "swan",
      mediaSha1: "eb7c447489d5ac7dc20d38c1a658b843f933102e",
      classification: "conversation",
      theme: "courtship",
      title: "The question had wings",
      body: "He raised both wings and came closer. I raised mine. We were trying to be inviting and had accidentally become enormous.",
    },
  ],
  "faye-thread": [
    {
      subject: "southern masked weaver",
      mediaSha1: "7596421494764dbf754b9deb836e8872bc3d9e32",
      classification: "event",
      theme: "movement",
      title: "Hanging by the draft",
      body: "I hung beneath the first loops to pull the next strip through. The nest held me. This was encouraging, though not the same as being finished.",
    },
  ],
  "ines-inkcap": [
    {
      subject: "Inca tern",
      mediaSha1: "c8a1d05b1bc35a0dee8d9d09644128c7065e0210",
      classification: "conversation",
      theme: "social",
      title: "One ledge, two opinions",
      body: "He said there was room for both of us. There was room for both our feet. Our moustaches are still negotiating.",
    },
  ],
  "oswin-broadback": [
    {
      subject: "Bison bison",
      mediaSha1: "54adcdb3705671cac9a8e7331a45caa4ce3ddfcb",
      classification: "personal",
      theme: "wonder",
      title: "The grass stayed low",
      body: "I stood still long enough for the grass to move around my legs. Nothing needed pushing. I checked twice.",
    },
  ],
  "cedric-crown": [
    {
      subject: "Cervus canadensis",
      mediaSha1: "1a61554e085786fbe8c13855106d68fede60dcd3",
      classification: "event",
      theme: "social",
      title: "The call carried farther",
      body: "I lifted my head and called. The valley sent part of it back. I answered before remembering the other elk was me.",
    },
  ],
  "hester-sweetlip": [
    {
      subject: "pale pitcher plant",
      mediaSha1: "192c83030ff8893e833c9a3f3b6d593a37145611",
      classification: "inspiring",
      theme: "transformation",
      title: "Flowers above the traps",
      body: "I raised my flowers well above the pitchers. Pollinators visit one part of me and survive the introduction to the other.",
    },
  ],
  "ambrose-armful": [
    {
      subject: "saguaro cactus",
      mediaSha1: "c805054fb9ba2db5c8896de5aa5aab15b152573f",
      classification: "conversation",
      theme: "social",
      title: "Everybody chose the top",
      body: "The birds arrived for the fruit and stood among the flowers. I had spent decades growing an arm. They treated it as a table.",
    },
  ],
  "otis-gulp": [
    {
      subject: "Pelecanus erythrorhynchos",
      mediaSha1: "9147e5e5ddf4d688143959a60c44a97f8982ad56",
      classification: "conversation",
      theme: "social",
      title: "Both bills open",
      body: "He opened his bill. I opened mine wider. Neither of us had brought a fish, so the demonstration continued on principle.",
    },
  ],
  "hugo-rim": [
    {
      subject: "Limulus polyphemus",
      mediaSha1: "138b1f4310eb86ea5dad30057d31a2538eb2facd",
      classification: "event",
      theme: "movement",
      title: "Foam around my feet",
      body: "The wave thinned into foam around my legs. I kept walking while the water changed its mind and went back without me.",
    },
  ],
  "edmund-oldring": [
    {
      subject: "giant sequoia",
      mediaSha1: "b30da34182a7ce8951b10db8fc3a5956361091d2",
      classification: "personal",
      theme: "wonder",
      title: "The others made scale",
      body: "I had never considered myself large. Then the smaller trees stood beside me and supplied the comparison.",
    },
  ],
  "maud-overhead": [
    {
      subject: "Corvus corax",
      mediaSha1: "b8055d51e56d411f792d9ae15bbfd3ce07cfd694",
      classification: "news",
      theme: "social",
      title: "Statement from the raven",
      body: "Opened my bill to make one point. The point came out loud enough to require several more.",
    },
  ],
  "beatrice-bark": [
    {
      subject: "Ursus americanus",
      mediaSha1: "2fdcc7f0e69f5a4bf8ead5a2f6933700eec7c5d8",
      classification: "personal",
      theme: "feeding",
      title: "Leaves beside my mouth",
      body: "I put my face around the trunk to reach the new leaves. The trunk stayed between us. Ate the leaves nearest the argument.",
    },
  ],
  "brio-beak": [
    {
      subject: "Atlantic puffin",
      mediaSha1: "c4f909029cef02bbbb8c8274447ea46e496d4318",
      classification: "personal",
      theme: "family",
      title: "No room for one more",
      body: "Caught another sand eel with my bill already full. Held the whole mouthful while deciding. The last fish used the pause to object.",
    },
  ],
  "moss-button": [
    {
      subject: "reticulated glass frog",
      mediaSha1: "590822718ee0a0c106925faad4389caaf660b355",
      classification: "personal",
      theme: "wonder",
      title: "Night through the leaf",
      body: "The leaf glowed green beneath me. I could see the dark beyond its edge and stayed where even the floor held light.",
    },
  ],
  "aster-reed": [
    {
      subject: "common darter dragonfly",
      mediaSha1: "f5f99069e230bd1ccb7d782e6dd22d5515c5ed20",
      classification: "event",
      theme: "movement",
      title: "The stem bowed first",
      body: "Landed on a dry stem and felt it bend. I lifted my wings to leave. It stopped bending, so I stayed and called that settled.",
    },
  ],
  "cora-curl": [
    {
      subject: "panther chameleon",
      mediaSha1: "4612536eff51a9ad8b3430cc384d0bdb46b5a1f0",
      classification: "personal",
      theme: "movement",
      title: "Tail kept the branch",
      body: "Both front feet chose the next branch. My tail kept the old one. I remained between decisions until the branches moved closer in the wind.",
    },
  ],
  "ellis-hook": [
    {
      subject: "satanic leaf-tailed gecko",
      mediaSha1: "7bc41eec5eb6ecba9f2c6747fccf9ff983a8121e",
      classification: "conversation",
      theme: "wonder",
      title: "The leaf looked back",
      body: "A real dead leaf settled beside me. I looked at it. It did not look back. I won, though the leaf remains unaware of the competition.",
    },
  ],
  "lark-spoon": [
    {
      subject: "roseate spoonbill",
      mediaSha1: "5393e178758b06b3774f06b65b63b79702ebc2c0",
      classification: "event",
      theme: "feeding",
      title: "Breakfast by touch",
      body: "Swept my bill through water too clouded to see. Something small touched the spoon and became the answer.",
    },
  ],
  "ada-dew": [
    {
      subject: "red-eyed tree frog",
      mediaSha1: "e1d4179d81ce86cdbc9d467daa7be57264a9daab",
      classification: "personal",
      theme: "wonder",
      title: "One eye for night",
      body: "I held the banana stem with every toe tucked close. Opened one red eye. Night had been waiting on all sides.",
    },
  ],
  "bramble-shortlegs": [
    {
      subject: "common wombat",
      mediaSha1: "d970eb22c747e9ecaab6d7f67ce95059b3de38ac",
      classification: "personal",
      theme: "wonder",
      title: "Paws under my face",
      body: "Put my face on my paws for a moment. The ground stayed close, the grass smelled right, and the moment became most of the afternoon.",
    },
  ],
  "wren-boulder": [
    {
      subject: "klipspringer",
      mediaSha1: "0c520c2851a3b045bc5fa2bd449b990fbd1038f1",
      classification: "conversation",
      theme: "wonder",
      title: "Both ears arrived first",
      body: "A sound came from behind the camera. Both ears turned before the rest of me. The rest has asked for more evidence.",
    },
  ],
  "mallow-fold": [
    {
      subject: "ground pangolin",
      mediaSha1: "ee256a5a0db7c007464a9b6311db5392ca8e3d53",
      classification: "event",
      theme: "movement",
      title: "Water below the scales",
      body: "Lowered my snout to the water and kept every scale above it. One ripple touched the underside anyway. I drank with less confidence after that.",
    },
  ],
  "sumi-smallhours": [
    {
      subject: "pygmy slow loris",
      mediaSha1: "7cc2e536b2f9307a72d9a0799bf3cd2f0a3918d8",
      classification: "personal",
      theme: "wonder",
      title: "Four hands, one pause",
      body: "Held two branches with four hands and looked into the dark. I was fully prepared to move as soon as the dark made the first move.",
    },
  ],
  "pip-pocket": [
    {
      subject: "Hawaiian bobtail squid",
      mediaSha1: "8ee3a18f67319c6dd45c4faa2b468b976686a1df",
      classification: "news",
      theme: "wonder",
      title: "Small enough for scale",
      body: "They placed a scale beneath me to show how small I am. My eye remains larger than their entire argument.",
    },
  ],
  "clove-clatter": [
    {
      subject: "blue-legged hermit crab",
      mediaSha1: "d22e5f02ef39f32230ce492d115bc4ae9209109c",
      classification: "personal",
      theme: "movement",
      title: "Blue legs, borrowed walls",
      body: "Put every blue leg outside the shell at once. The house remained behind me and around me, which is the arrangement I prefer.",
    },
  ],
  "nellie-nudge": [
    {
      subject: "Florida manatee",
      mediaSha1: "aba9a528563e81d8a0b5043d359fc87e7711ee5c",
      classification: "conversation",
      theme: "social",
      title: "Muzzle first",
      body: "Came close enough for my whiskers to inspect the visitor. The visitor held still. Good. We had agreed on the important part.",
    },
  ],
  "sorrel-spring": [
    {
      subject: "lesser Egyptian jerboa",
      mediaSha1: "c263066d24a1ee1c33c581da1909c65851cd18a2",
      classification: "event",
      theme: "danger",
      title: "Still before the leap",
      body: "Heard sand move to my left. Kept both small hands close and every large part of the decision in my hind legs.",
    },
  ],
  "alba-longwing": [
    {
      subject: "northern royal albatross",
      mediaSha1: "2527881b2d12ddbd9941c08d183bff9845e54d2a",
      classification: "inspiring",
      theme: "movement",
      title: "The turn held me",
      body: "Banked into the wind until one wing pointed at sea and one at sky. The air held the angle I would never trust to land.",
    },
  ],
  "ludo-leap": [
    {
      subject: "regal jumping spider",
      mediaSha1: "4a4bd8407f474bb534b5dd688b314f4909cc7344",
      classification: "personal",
      theme: "wonder",
      title: "Eight eyes forward",
      body: "Turned all the way toward the enormous face. My front eyes saw it clearly. The others confirmed there was nowhere sensible it was not.",
    },
  ],
  "basil-backward": [
    {
      subject: "slipper lobster",
      mediaSha1: "e20e6efadfc41b9de4bac57cdfd99c6d05a6d6a1",
      classification: "personal",
      theme: "wonder",
      title: "Antennae laid flat",
      body: "I set both broad antennae against the rock and disappeared as much as a lobster shaped like a shovel can disappear.",
    },
  ],
  "berta-bank": [
    {
      subject: "North American beaver",
      mediaSha1: "1adf095ae8d8804c517346f2f93854ab4cc51d75",
      classification: "personal",
      theme: "wonder",
      title: "Tail beside the work",
      body: "Sat beside the water with my tail flat behind me. For once it was not steering, warning, or dragging mud. It looked surprised by the rest.",
    },
  ],
  "rufus-russet": [
    {
      subject: "red fox",
      mediaSha1: "87ec0d9c8c2393ec98cd2bf7cc4dbfcb8a57118e",
      classification: "personal",
      theme: "weather",
      title: "Snow kept the shape",
      body: "Curled until my nose found my tail. Snow settled around the outside and left one fox-shaped place warm.",
    },
  ],
  "elspeth-reach": [
    {
      subject: "Muusoctopus sp.",
      mediaSha1: "252f3ddad673282122f60dea0a23f66139f8b048",
      classification: "conversation",
      theme: "social",
      title: "The orange neighbor",
      body: "Curled every arm around myself beside the little orange anemone. It remained open. One of us was handling the visitor better.",
    },
  ],
  "delphine-silkspill": [
    {
      subject: "common milkweed",
      mediaSha1: "2aaec551ec0bad047ddee09f7526b3d441821b92",
      classification: "personal",
      theme: "family",
      title: "Pods before opening",
      body: "I held the pods closed while every seed inside prepared to leave. Order is easiest before the children meet wind.",
    },
  ],
  "agnes-splinter": [
    {
      subject: "Dryocopus pileatus",
      mediaSha1: "0f1ac788c494027725127cb0f68c506dd16d919b",
      classification: "news",
      theme: "feeding",
      title: "The opening got larger",
      body: "Found one soft place in the trunk and struck it again. The hole grew. So did the list of insects who had hoped I would stop at one.",
    },
  ],
  "ansel-threadbark": [
    {
      subject: "Great Basin bristlecone pine",
      mediaSha1: "d8d8461cf318d1686a782a4a8a34196f136ef1cd",
      classification: "inspiring",
      theme: "transformation",
      title: "Green at one edge",
      body: "Most of the trunk stands bare in the weather. One living edge still carries needles. I no longer confuse narrow with finished.",
    },
  ],
};
