import type { SampleCharacterArc } from "./sample-character-arcs.js";

/** Root-approved deep-sea batch 09. Source taxonomy remains intentionally conservative where captions do. */
export const DEEPSEA_NINE_CHARACTER_ARCS: readonly SampleCharacterArc[] = [
  {
    "characterId": "romy-helix",
    "identityNameBase": "Romy Helix",
    "platform": "rss",
    "bio": "An Iridogorgia coral. Helpful in every direction at once.",
    "location": { "name": "Deep seamount in the central North Atlantic", "coordinates": { "lat": 31, "lng": -43 } },
    "episodes": [
      { "classification": "conversation", "subject": "Iridogorgia coral", "platform": "rss", "mediaSha1": "40ec7c41f6b5833e0b16cc95fcfda5a86f843b1e", "theme": "social", "title": "Hold your claws still", "body": "The shrimp wanted to help. He offered to remove something from one of my branches.\n\nI asked which thing.\n\nHe pointed with a claw. I could feel the point touching me, so I asked him not to close it while we discussed this.\n\nHe said the little pale bits looked untidy. There were so many of them. Perhaps I hadn't noticed.\n\nI opened the nearest polyp.\n\nHe drew his claw back. I opened another. He backed into a third. I let that one stay closed until he'd stopped apologizing.\n\nHe has offered to bring me something instead. I told him to describe it before putting it down." },
      { "classification": "conversation", "subject": "Iridogorgia coral", "platform": "facebook", "mediaSha1": "f0ba9e5bd80a8fb9da852694eadb78810840fdf0", "theme": "social", "title": "Come one, come several", "body": "I told one crinoid he could stay. Apparently I said it in a very welcoming shape.\n\nThere are now crinoids on the branch I use to gesture about the crinoids." },
      { "classification": "news", "subject": "Iridogorgia coral", "platform": "linkedin", "mediaSha1": "1d2b7e7420b24aa9ad5dc86a64f55de2ffbceef8", "theme": "feeding", "title": "The hungry section", "body": "I attempted to think about the whole ocean. A small piece of it brushed one of my mouths, and I ate it.\n\nI am still thinking about the ocean, but that piece was excellent." },
      { "classification": "conversation", "subject": "Iridogorgia coral", "platform": "rss", "mediaSha1": "fef6dcd6a244778ce629c4f86891f3704b5188ae", "theme": "social", "title": "The little grip", "body": "I can tell when he arrives. A small weight on a branch, then another, then the peculiar stop while he decides where to put the rest of his legs.\n\nI used to wait for that stop so I could suggest a better place. There was always a better place. Higher, where the current was stronger. Lower, where he wouldn't pull. He would go where I suggested. I was pleased with how well we understood each other.\n\nThen one day he arrived and did not stop. He climbed straight past the place he used to choose.\n\nI felt proud for a moment. Then I wished he were slower.\n\nToday he has settled on the awkward branch again. I can feel him gripping it. I have thought of three better places and said nothing.\n\nHe's taking his time." },
      { "classification": "news", "subject": "Iridogorgia coral", "platform": "linkedin", "mediaSha1": "e3b07ab5deea88354b978eaf7703b08765858985", "theme": "wonder", "title": "Almost a circle", "body": "Someone said I had come full circle. I asked him to follow the branch and check.\n\nHe's still going. It was an unkind way to make a point, but he started it." }
    ]
  },
  {
    "characterId": "oswald-cup",
    "identityNameBase": "Oswald Cup",
    "platform": "linkedin",
    "bio": "A Caulophacus glass sponge. He knows the water, not the view.",
    "location": { "name": "Deep seamounts south of Midway, North Pacific", "coordinates": { "lat": 27, "lng": -177 } },
    "episodes": [
      { "classification": "news", "subject": "Caulophacus glass sponge", "platform": "linkedin", "mediaSha1": "6e11b2847fa18b6636ed8ded872d4d920760422d", "theme": "wonder", "title": "Long neck, short answer", "body": "Someone at the bottom asked what I could see from up here. I said I hadn't got eyes.\n\nHe asked why I'd gone to all that trouble." },
      { "classification": "conversation", "subject": "Caulophacus glass sponge", "platform": "rss", "mediaSha1": "8eaab98186fb4180b56e50b3b0e69e83ab03c0fa", "theme": "social", "title": "I didn't feel it", "body": "He found the little fold before I did. Tucked himself into it with all those legs and announced that it was a fine place.\n\nI said there wasn't a fold there.\n\nHe said he was in it.\n\nI tried to account for him. I knew where the water passed, where I held against the current, where something brushed my surface. I couldn't turn any of that into a picture of the place he meant.\n\nHe described it again. Patiently this time. There was a narrow opening, a curve, a darker bit. He said it would look obvious if I could see it.\n\nI couldn't. He stayed anyway.\n\nNow when something small moves there, I don't have to know what I look like to know who it is." },
      { "classification": "conversation","subject":"Caulophacus glass sponge","platform":"substack","contentType":"article","mediaSha1":"cb24aa3401da66c06dbddaa202464908c77a5292","theme":"social","title":"The resemblance problem","body":"The lobster returned with unsettling news. There were two other sponges beside me, and we looked alike.\n\nI asked how alike.\n\nHe said I would understand if I could see us. We had already established that I couldn't, but he enjoys keeping that possibility alive.\n\nFor a while I disliked the others. I had worked my way into this particular shape without even knowing what it was, and apparently they had arrived at much the same conclusion. I asked which of us was best.\n\nThe lobster went quiet.\n\nThen he climbed back into the fold where he sleeps. I could feel him rearranging himself, catching one leg, tugging it free. He said the middle one was larger. The other had a nicer curve.\n\nI waited for him to finish.\n\nHe didn't. He was asleep.\n\nI have decided against asking the question again. There is a great deal to be said for being the one with his leg stuck in it."}
    ]
  },
  {
    "characterId": "severin-quiet",
    "identityNameBase": "Severin Quiet",
    "platform": "facebook",
    "bio": "A pale deep-sea lizardfish. Trying to look less alarming.",
    "location": { "name": "Central North Pacific abyssal seafloor", "coordinates": { "lat": 27.5, "lng": -166.7 } },
    "episodes": [
      { "classification": "conversation", "subject": "Bathysaurus deep-sea lizardfish", "platform": "facebook", "mediaSha1": "50f734b1bfe9c388c6c7339da6d1107a05f80924", "theme": "social", "title": "The softer face", "body": "I've been keeping my mouth closed when she comes by. It seems to help.\n\nToday she came closer and asked if I was ill." },
      { "classification": "conversation", "subject": "Bathysaurus deep-sea lizardfish", "platform": "rss", "mediaSha1": "26d9c5c017ad8b711cb694989a078ac2711efc22", "theme": "social", "title": "A proper apology", "body": "I frightened him. I didn't mean to, which I kept trying to explain while he got farther away.\n\nThe farther away he went, the wider I opened my mouth to make myself clear.\n\nEventually I noticed the difficulty.\n\nI stayed on the bottom and let him put a comfortable amount of ocean between us. There was plenty. I had no objection to his using it.\n\nWhen he stopped, I closed my mouth.\n\nWe sat like that for a while. I wanted to say I was sorry. I wanted him to know I had noticed. But every version of that involved opening my mouth again.\n\nHe moved a little closer before leaving. I have decided to count that." },
      { "classification": "conversation","subject":"Bathysaurus deep-sea lizardfish","platform":"substack","contentType":"article","mediaSha1":"739a9051fd64ed6527cb8c2039ef9ce3098e20c0","theme":"social","title":"Beside the dangerous end","body":"My little neighbor stopped beside my jaw.\n\nThere is a great deal of me available. A long back. A tail that gives everyone ample warning. He chose the part my acquaintances generally discuss from farther away.\n\nI kept still. This is something I do well, although usually for reasons nobody finds reassuring.\n\nHe reached, drew back, tried a different direction. I remembered my last attempt at an apology, when every explanation had required more teeth. So I offered no explanation. I let him be small beside me.\n\nAfter a while I began to feel remarkably gentle. I wondered whether he could tell. I wondered whether he might mention it to somebody.\n\nHe moved on without looking back.\n\nI stayed in place, enormously pleased with myself, until a shrimp passed safely beyond my reach. By then I had been such a good person for so long that I was furious with both of them."}
    ]
  },
  {
    "characterId": "dorian-sulk",
    "identityNameBase": "Dorian Sulk",
    "platform": "x",
    "bio": "A Chaunacops sea toad. Enjoying himself quietly.",
    "location": { "name": "Musicians Seamounts, northeast of Hawaii", "coordinates": { "lat": 23, "lng": -158 } },
    "episodes": [
      { "classification": "conversation", "subject": "Chaunacops sea toad", "platform": "x", "mediaSha1": "a194ac5fbb072a77dc62802900d4eb985c0a4d34", "theme": "social", "title": "Resting opinion", "body": "I was enjoying myself. Someone came over to ask what was wrong, so now there is an answer." },
      { "classification": "event", "subject": "Chaunacops sea toad", "platform": "rss", "mediaSha1": "cc533c43dd73c2c9da559a6655f155de286a3c4f", "theme": "movement", "title": "Passing through", "body": "I took one step and stopped. There was a better place for the other fin, but getting it there required admitting the first step had been poorly chosen.\n\nA fish went past. Then back. He asked whether I needed help.\n\nI said I was looking at something.\n\nHe settled beside me to see it too. We stayed there for a while, both looking at a patch of bare rock. Every so often he edged closer. I thought he might be about to leave, but he was only trying to work out what he'd missed.\n\nEventually I took the second step.\n\nHe gasped. I have no idea what he thinks happened." },
      { "classification": "news","subject":"Chaunacops sea toad","platform":"substack","contentType":"article","mediaSha1":"003e3521297e642169b71782984075b7548fb359","theme":"wonder","title":"Apparently I am scarlet","body":"Until the light arrived, I thought the most conspicuous thing about me was my opinion.\n\nThe water turned bright. Every little ridge on my skin stood out. A passing fish stopped, looked at me, and said something about red.\n\nI have spent a considerable amount of my life being left alone on dark rocks. Now I learn there has been a whole other version of me, waiting for someone to bring the right kind of light. Apparently that version looks enthusiastic.\n\nThe fish said I was beautiful.\n\nI told her I had done nothing differently.\n\nShe stayed. I disliked the inspection, but I had also noticed that she had stopped inspecting the rocks. We sat through a long, uncomfortable interval in which I could find no way to make her compliment less pleasant.\n\nWhen the light moved away, she went with it.\n\nI am back to being difficult to see. I had preferred this until quite recently."},
      { "classification": "event","subject": "Chaunacops sea toad", "platform": "youtube", "contentType": "video", "mediaSha1": "7f32a429cae0d5d339cc3a66014791645b8c2ee5", "theme": "movement", "title": "I had to make myself smaller", "body": "I sat there being an imposing presence until I needed to swim.\n\nHad to make myself smaller first. It was an undignified amount of preparation for leaving people alone.", "video": {"videoId": "CH5TFffP6VE", "title": "The Magically Deflating Sea Toad", "uploader": "NOAA Ocean Exploration", "channelUrl": "https://www.youtube.com/@oceanexplorergov", "watchUrl": "https://www.youtube.com/watch?v=CH5TFffP6VE", "primarySourceUrl": "https://archive.oceanexplorer.noaa.gov/okeanos/explorations/ex1606/logs/photolog/dive6.html", "thumbnailUrl": "https://archive.oceanexplorer.noaa.gov/okeanos/explorations/ex1606/dailyupdates/media/aug6-1-hires.jpg"}}
    ]
  },
  {
    "characterId": "cato-many",
    "identityNameBase": "Cato Many",
    "platform": "rss",
    "bio": "A yellow stalked crinoid. Generous with advice until dinner intervenes.",
    "location": { "name": "Deep North Atlantic seamount", "coordinates": { "lat": 31, "lng": -51 } },
    "episodes": [
      { "classification": "conversation", "subject": "yellow stalked crinoid", "platform": "rss", "mediaSha1": "1c2f2948fdbf975f4f1f7f74390446e5963e543f", "theme": "social", "title": "One bright place", "body": "A little one grew below us. At first I mistook the thin pale line for something caught on the rock. Then there were arms.\n\nHe kept them so close together that I wanted to explain how much water he was missing. I had an explanation ready. It involved opening out, being less afraid, several things that are easy to say when you already reach over the rock.\n\nThen a small current found the hollow where he was. His arms opened into it.\n\nHe ate before I did.\n\nI felt pleased for him. There was something else in there too. I will not be discussing that with the little one." }
    ]
  }
];
