import type { SampleCharacterArc, SampleCharacterEpisode } from "./sample-character-arcs.js";

type AuthoredEntry = readonly [SampleCharacterEpisode["theme"], string, string];

/** Static prose with intentional text-only defaults and individually reviewed scene bindings. */
function unbound(subject: string, entries: readonly AuthoredEntry[]): SampleCharacterEpisode[] {
  return entries.map(([theme, title, body]) => ({
    subject,
    mediaSha1: REVIEWED_SCENE_IMAGES[`${subject}:${title}`] ?? null,
    theme,
    title,
    body,
  }));
}

const REVIEWED_SCENE_IMAGES: Readonly<Record<string, string>> = {
  "red panda:Face first": "2843095a7583d16b1e021d507f4f12d9094a2bd7",
  "fennec fox:Room for the ears": "f75dbf0c7b4389ca11cb83932fdf0ae0b262af51",
  "American pika:Too wide for the doorway": "3ad59da6eb348ba742c65cb1c6303ff9748117a6",
  "Arctic fox:White fur, dark stones": "4166db4f4461285fb2e09caacdea9a314562cadf",
};

export const LAND_CHARACTER_ARCS: readonly SampleCharacterArc[] = [
  {
    characterId: "nib-willow", identityNameBase: "Nib Willow", platform: "instagram",
    bio: "A red panda who has found the perfect sleeping branch and would like the sun to stop moving.",
    location: { name: "Singalila montane forest", coordinates: { lat: 27.09, lng: 88.03 } },
    episodes: unbound("red panda", [
      ["movement", "Face first", "I came down the trunk headfirst, beautifully. Near the bottom I discovered how much of a descent depends on knowing where the bottom is. The last little bit was mostly face."],
      ["feeding", "Tender selection", "Held a bamboo spray in one paw and picked out the tender leaves. Dropped the spray while rejecting a leaf. Ate the rejected leaf on my way down to collect the rest."],
      ["weather", "Chasing the warm patch", "The sun moved off my stomach. I shifted along the branch. It moved again. After three adjustments I was sleeping with my head lower than my feet, which apparently is what the sun wanted."],
      ["social", "Already occupied", "Marked the low branch, then noticed another red panda watching from above. Finished very thoroughly. Had to walk past him afterward with the same bottom I had just made so much of."],
      ["wonder", "Caught by the tail", "Woke with my tail over my nose and an urgent feeling that somebody was too close. I pushed it away. Cold nose. Pulled it back. Whoever it was could stay."],
      ["movement", "The fork with the lump", "Tried the neighboring tree. Better view, softer moss, no lump under my ribs. Could not sleep. Came back and put the lump exactly where it hurts."],
      ["feeding", "A change of menu", "Found a fallen berry and carried it up to my branch. It rolled off while I was arranging my paws. Watched it land beside the bamboo. Some meals are very determined to be bamboo."],
      ["weather", "Rain underneath", "I tucked myself beneath the thickest leaves before the rain. The first drop ran down the branch and entered from under my chin. I had prepared for rain from above, like an idiot."],
      ["social", "The other smell", "Somebody marked my tree while I was out. I sniffed the trunk, the fork, the low branch, the trunk again. By the time I finished being offended, I was late for my nap."],
      ["wonder", "Leave the lump", "A piece of bark loosened on my sleeping branch. I worried it with a claw until it fell. The lump is gone. I keep reaching underneath myself to check, as though I could put it back."],
    ]),
  },
  {
    characterId: "juniper-ears", identityNameBase: "Juniper Ears", platform: "facebook",
    bio: "A fennec fox with exceptional hearing and a long list of noises she would prefer not to have identified.",
    location: { name: "Erg Chebbi dune margin", coordinates: { lat: 31.17, lng: -4.0 } },
    episodes: unbound("fennec fox", [
      ["feeding", "Excellent hearing", "Something scratched beneath the sand. I dug until my ears were full of it. The scratching stopped. Now I can hear one grain moving inside my left ear and nothing else worth eating."],
      ["social", "Too near to ignore", "My neighbor chews with his mouth open at the entrance of his burrow. I went over to object and he offered me the last bit. It was very good. I will object again tomorrow."],
      ["movement", "Room for the ears", "Enlarged the tunnel this morning. My shoulders already fitted, but every time I turned my head the ceiling folded an ear. I refuse to spend another day agreeing with both walls."],
      ["weather", "The loud root", "A dry root tapped against the sand all night. I pounced on it twice before the wind stopped and showed me what I had been hunting. I carried it away anyway. I need sleep."],
      ["feeding", "Buried too well", "I hid a scrap beside a small bush. The wind buried the bush. Found the scrap by smell, but had to dig through a disappointing amount of yesterday to get it."],
      ["danger", "A shadow at dawn", "The sky darkened over my back and I reached the burrow before I had decided to run. Stayed inside until dusk. Spent most of the day pretending I had meant to come home early."],
      ["social", "Chew quietly", "Went to find my noisy neighbor. His entrance was empty. Waited, listening for the chewing I had complained about. He came back with a beetle and I sat much too close while he ate it."],
      ["wonder", "Under the quiet", "Lay with my chin on the sand after everyone settled. Tiny feet kept moving underneath. All that dark, full of errands. Then my stomach growled and ruined the small ones."],
      ["social", "He heard that", "Tried to approach my neighbor quietly. Placed each foot carefully. Held my tail clear of the scrub. He turned before I reached him. I had forgotten the ears were not exclusive to me."],
      ["social", "Better from here", "My neighbor ate outside my burrow tonight. I could hear every crunch. Moved farther inside, then came back and put my chin on my paws beside him. He chewed directly into my best ear."],
    ]),
  },
  {
    characterId: "sumi-smallhours", identityNameBase: "Sumi Smallhours", platform: "instagram",
    bio: "A pygmy slow loris who leaves early, arrives late, and remembers every useful wound in a tree.",
    location: { name: "Cat Tien lowland forest", coordinates: { lat: 11.42, lng: 107.4 } },
    episodes: unbound("pygmy slow loris", [
      ["feeding", "Lunch on a string", "The gum stretched from the bark to my mouth. I moved my head back to break it. More gum. For a while I was a very small animal on the end of a very long meal."],
      ["movement", "Hand already occupied", "Reached for the next branch. My other hand was holding the branch I needed to let go of, and a foot had joined in. I remained there, considering which part of me had started this."],
      ["weather", "Wet all the way through", "The rain flattened my fur. I looked down at my narrow wet wrist and briefly worried about how little of me had been holding me up. Tightened my grip. The wrist continued doing its job without looking any more reassuring."],
      ["social", "Your branch, briefly", "Another loris came toward me on the same branch. I moved underneath to let her pass. She moved underneath too. We hung nose to nose until she sighed, which I thought was unfair."],
      ["feeding", "The good wound", "The tree had closed the little place where I used to find gum. I worked at the bark until a fresh bead appeared. Licked it. Returned twice to make certain the tree understood what we had agreed."],
      ["danger", "Hold everything", "Something large moved below. I froze with one hand halfway to my mouth. It passed. My hand remained there a little longer, carrying on with the fear after the rest of me had finished."],
      ["wonder", "Bloom within reach", "Pushed my face into a flower for nectar. Came out carrying yellow dust. Rubbed my cheek with a hand, then scratched my ear. I have managed to spread the flower considerably farther than I moved."],
      ["feeding", "The clean hand", "Licked the gum off one hand before moving on. Put that hand straight back on the sticky bark to clean the other. I have been taking turns being almost finished for some time."],
      ["social", "No hurry now", "She was at the narrow branch again. I stopped well before it and let her cross. She stopped beside me afterward. We sat there long enough that I could no longer blame the branch for wanting to stay."],
      ["feeding", "Saved for later", "Left a little gum on my favorite tree because I was full. Came back before dawn. It was still there. I had spent the whole journey worrying about the appetite of everyone else in the forest."],
    ]),
  },
  {
    characterId: "pella-wideawake", identityNameBase: "Pella Wideawake", platform: "x",
    bio: "A Philippine tarsier who sees most things coming and still reacts as though they have insulted her.",
    location: { name: "Bohol forest understory", coordinates: { lat: 9.72, lng: 124.03 } },
    episodes: unbound("Philippine tarsier", [
      ["movement", "Nowhere to put the speed", "Leapt to a very thin trunk. It bent, returned, and sent me partway back. I held on through the second opinion."],
      ["feeding", "The quieter cricket", "Followed a cricket's call until I was close enough to jump. It stopped. Another began behind me. I turned my whole head to give the first one time to reconsider."],
      ["wonder", "Insufficient darkness", "The moon came through a gap and lit the leaf I was watching. I could see every vein, every nick, every empty place where a beetle was failing to be."],
      ["danger", "Held by five fingers", "A snake moved along the branch above. I crossed the gap so fast my hand arrived before I did. Spent a moment hanging there grateful to the smallest part of myself."],
      ["feeding", "Caught the wrong edge", "Pounced at a beetle on the end of a leaf. Caught the leaf. It folded around my face, making the beetle's departure a private matter."],
      ["social", "The branch shook first", "Felt somebody land before I saw him. He was clinging to the other side of my trunk. We each leaned around to inspect the other and continued seeing only bark."],
      ["movement", "Reduced ambition", "Picked a closer trunk for my next leap. Landed exactly where I meant to. Nobody was there to appreciate the improvement, so I stayed awhile appreciating it myself."],
      ["weather", "Everywhere at once", "Rain started on the leaves around me. I turned toward the first noise, then the second, then gave the entire forest a very hard stare."],
      ["feeding", "Stay with the meal", "A moth settled on my wrist while I watched a cricket. I noticed the tickle, shook my hand, and continued hunting. Realized what I had done much later. Still thinking about it."],
      ["wonder", "Before the pale part", "Returned to my sleeping tangle before dawn. One last movement below. I looked. Falling leaf. Watched it all the way down anyway, with the enormous eyes I apparently must use for everything."],
    ]),
  },
  {
    characterId: "orla-reach", identityNameBase: "Orla Reach", platform: "facebook",
    bio: "A short-beaked echidna whose nose keeps making commitments her shoulders cannot honor.",
    location: { name: "Tasmanian dry woodland", coordinates: { lat: -42.5, lng: 147.1 } },
    episodes: unbound("short-beaked echidna", [
      ["feeding", "Further than the rest", "My nose fitted into the rotten log. My tongue fitted farther. My shoulders stopped outside. Ate lunch stretched across the entrance while a perfectly good patch of shade sat just behind my rump."],
      ["movement", "Backing out helped", "Tried to turn around between two roots. There was room for one end of me or the other. After a long pause I backed out, bringing enough loose bark to imply I had been digging."],
      ["danger", "Too late for conversation", "A heavy footstep. I dug down and presented my spines. It passed. When I came up, I was facing the opposite direction and had forgotten which ants I was after."],
      ["feeding", "Pause between mouthfuls", "A sneeze interrupted my tongue halfway into the log. Everything withdrew at once. Stood with my nose lifted, waiting for another sneeze, while the ants continued organizing themselves into a meal I was not having."],
      ["weather", "The hollow held water", "My usual hollow filled in the rain. Put a foot in, took it out, put it in again. The second attempt confirmed that I needed somewhere else to sleep, which the first attempt had been trying to tell me."],
      ["wonder", "A log coming apart", "The old log split under my claws today. Inside it was soft, warm, busy, and nothing like the hard thing I had been walking around. I stuck my whole nose in and forgot to be impressed."],
      ["social", "Please stop following", "Another echidna followed me around a stump. I stopped; he stopped. I reversed; he reversed. I finally climbed over a root. He went around it and was waiting, which felt unnecessarily competent."],
      ["movement", "Across the wet bit", "Swam across the narrow creek because the other bank smelled interesting. Climbed out heavy and dripping. It smelled interesting from there too, but mostly like a wet echidna."],
      ["feeding", "A longer way in", "Returned to the log that trapped my shoulders. Dug underneath this time. Reached the soft middle in comfort, then fell asleep with my nose inside. Woke hungry in an excellent position."],
      ["weather", "Mine after all", "The hollow dried out. I nosed around the edges before settling. Turned twice, tucked my feet under, breathed out. A twig poked my belly. Knew exactly which twig without looking."],
    ]),
  },
  {
    characterId: "finch-fidget", identityNameBase: "Finch Fidget", platform: "instagram",
    bio: "A quokka who objects to being called cheerful while she is trying to chew.",
    location: { name: "Rottnest Island scrub", coordinates: { lat: -32.0, lng: 115.5 } },
    episodes: unbound("quokka", [
      ["feeding", "This is my chewing face", "The other quokka took the leaf I was reaching for. I chewed what I had and watched her. My face may have looked friendly. The chewing was extremely pointed."],
      ["movement", "Higher than breakfast", "Climbed into a shrub for a fresh shoot. Ate it, looked down, and discovered that the shoot had been the only part of my plan involving that height."],
      ["weather", "One foot outside", "The shade was just wide enough until the sun moved. Pulled my foot in. The other foot went out. I am beginning to understand why the larger quokka arrived before me."],
      ["social", "Saved you a leaf", "Kept the last leaf near my paw when my neighbor approached. She sniffed it and moved on. I ate it quickly so it would look like that had been my intention."],
      ["feeding", "The tough end", "Started a stem from the wrong end and kept chewing because I had started. My jaw got tired. Put it down with the good end facing me for when I become sensible."],
      ["wonder", "Fresh dirt", "A root came loose in the damp earth and brought up a smell I had never noticed under the dry crust. I stood with my nose in the hole until someone stepped on my tail."],
      ["social", "An opening appeared", "The big quokka left the cool spot. I moved in before the flattened grass could stand up. She returned almost immediately. I shut my eyes with enormous conviction."],
      ["movement", "Coming down backward", "Found another excellent shoot above my head. Climbed, ate, and came down backward this time. Stood at the bottom chewing very slowly in case anyone wanted to ask about my technique."],
      ["courtship", "Practicing indifference", "He grazed beside me. I chose a leaf facing away from him and chewed it as if I had never found anything so interesting. When he left, I had eaten the same bare stalk for quite a while."],
      ["feeding", "The good end waited", "Found the stem I had abandoned. Turned it around and ate the tender end first. Then the tough part. I could have spared myself several days of feeling clever about this."],
    ]),
  },
  {
    characterId: "sorrel-spring", identityNameBase: "Sorrel Spring", platform: "x",
    bio: "A lesser Egyptian jerboa with too much departure and a developing interest in stopping.",
    location: { name: "Sinai gravel desert", coordinates: { lat: 29.6, lng: 33.9 } },
    episodes: unbound("lesser Egyptian jerboa", [
      ["movement", "Past the seed", "Saw a seed. Hopped toward it. Landed beyond it. Turned, hopped back, landed beyond it again. Approached the third time in small, humiliating increments."],
      ["weather", "Closed for heat", "Plugged my burrow entrance against the day. A loose grain fell on my nose as I settled. Reopened the whole entrance to get it out, then spent the next while restoring my own good decision."],
      ["feeding", "Both hands full", "Picked up a seed in each little hand. An owl called. My legs were ready to leave, but my mouth was still deciding which seed to save."],
      ["wonder", "A clean patch of sand", "Dug a shallow dip and rolled in it until my fur felt right. Got up looking carefully groomed beside a hole that looked as if something terrible had happened."],
      ["danger", "The useful crooked route", "Something rushed behind me. I leapt left, right, left, nowhere near where I had intended. Reached cover alive and spent a long time trying to remember where dinner was."],
      ["movement", "Tail arrived separately", "Cleared a low shrub. My tail brushed it on the way past and I made another enormous leap, escaping the last part of myself."],
      ["social", "Small greeting", "Met another jerboa near the seed patch. We touched noses. Neither of us moved for a moment. Then a twig cracked and we became very far apart."],
      ["feeding", "Slow enough to taste", "A seed lodged between two stones. Sat down and worked it loose with my paws. Ate it there. My legs seemed surprised to be included in a meal only as furniture."],
      ["weather", "The sand changed sides", "The wind shifted the little ridge beside my entrance. I arrived on the familiar side and found no hole. Dug angrily for a moment, then walked around my landmark."],
      ["movement", "One quiet arrival", "Came back to the seed patch and saw the other jerboa. Stopped well short of her this time. Took the last few steps slowly. There are occasions when these ridiculous feet can behave."],
    ]),
  },
  {
    characterId: "tully-tumble", identityNameBase: "Tully Tumble", platform: "linkedin",
    bio: "A rock hyrax whose morning sunning is essential work and whose alarm calls sometimes need correcting.",
    location: { name: "Matobo granite outcrops", coordinates: { lat: -20.55, lng: 28.5 } },
    episodes: unbound("rock hyrax", [
      ["weather", "Available after warming", "I reached the sunniest rock first and stretched out across it. Several others joined me. I remained the first to arrive, though very little of me remained in the sun."],
      ["danger", "A very low eagle", "Gave the alarm when a shadow crossed our ledge. Everyone scattered. The shadow belonged to grass above us. I kept watching the sky until it seemed too late to explain."],
      ["social", "The warm side", "A youngster pressed against my side while we rested. I shifted away; he followed. Eventually I stopped moving. When he left, that side got cold, which I had not taken into account."],
      ["feeding", "A better mouthful", "Climbed past perfectly adequate leaves to reach one high shoot. It bent away each time I stretched. Ate the adequate leaves on the descent with a seriousness they had not previously deserved."],
      ["movement", "Sound footing", "My feet held beautifully on the steep face. Paused to admire the view. A little stone slid beneath one toe and I immediately became interested in the view from lower down."],
      ["wonder", "The echo kept going", "Called across the rocks. Something answered with excellent volume and terrible timing. I called again to correct it. Spent longer than I care to admit improving an echo."],
      ["social", "A small place left", "Found my sunning ledge crowded. There was room beside the youngster who used to lean on me. I lowered myself into it gradually, as if the warmth were a coincidence."],
      ["danger", "This one had feathers", "Saw an eagle banking beyond the ridge and called once. The whole group vanished into cracks. When we came out, nobody congratulated me. I would also like to forget the grass incident."],
      ["feeding", "Chewing during the lookout", "Chose a high lookout with a good view of every approach. From here I can see the eagle, the path, and someone eating the leaves I had pulled down. I can stop exactly one of these things by leaving my excellent lookout."],
      ["weather", "The other end of the ledge", "Cloud covered my favorite rock. I followed the remaining light to the far end and found three others already there. Lay down without announcing that I had discovered a better position."],
    ]),
  },
  {
    characterId: "wren-boulder", identityNameBase: "Wren Boulder", platform: "instagram",
    bio: "A klipspringer who trusts a rock the size of a mouthful more than a broad patch of grass.",
    location: { name: "Serengeti granite kopjes", coordinates: { lat: -2.58, lng: 34.93 } },
    episodes: unbound("klipspringer", [
      ["movement", "Enough rock", "Landed with all four feet on the tip of a boulder. There was exactly enough room. Sneezed. Needed rather more room for that."],
      ["social", "My turn to watch", "He browsed while I watched the grass below. Then he raised his head and I lowered mine. We both kept one eye on the same especially good leaf until he finally looked away."],
      ["feeding", "Within reach, almost", "Stretched toward a flower from my narrow perch. It brushed my lips and swung back. I waited for the wind to bring it again. For once, the thing making lunch difficult also delivered it."],
      ["danger", "Below the safe ledge", "A leopard moved through the rocks beneath us. I stood so still that a fly settled on my nose. Let it walk. Have been thinking about that fly ever since."],
      ["movement", "Too much ground", "He crossed the grass straight toward me. I went around by the rocks to meet him safely. Arrived where he had started. Whistled for him. He looked across from my old perch, and I could see him deciding whether to come and get me."],
      ["weather", "A dry little island", "The rain left one sheltered shelf untouched. I stepped onto it and shook myself. The shelf was no longer dry, but at least I knew who to blame."],
      ["social", "Stay where I can see you", "He went around the boulder and disappeared. I whistled. He appeared at the other side, still chewing. I chewed too, although I had nothing in my mouth."],
      ["wonder", "The crack opened green", "A shoot grew from a crack I had stepped over all dry season. I sniffed it, tasted the tip, and left the rest. Came back before sunset to see how much patience had achieved."],
      ["movement", "The landing was fine", "Jumped down to the next ledge. My hooves landed neatly. My chin met a branch I had not included in the landing. Stood there with leaves in my mouth and made the best of it."],
      ["feeding", "Some for the return", "The little shoot in the crack had grown. Took two leaves and moved on. He reached it after me and took another. I almost went back to discuss the rate of growth."],
    ]),
  },
  {
    characterId: "fern-longnose", identityNameBase: "Fern Longnose", platform: "facebook",
    bio: "A white-nosed coati who is following one promising smell and will catch up with everyone in a moment.",
    location: { name: "Corcovado lowland forest", coordinates: { lat: 8.54, lng: -83.57 } },
    episodes: unbound("white-nosed coati", [
      ["feeding", "Followed the nose", "Found a wonderful smell under a log. Pushed my nose in, dug beside it, pushed farther. When I looked up, the group had left. The smell had better be wonderful."],
      ["social", "Last again", "Caught up with the others carrying a grub. Ate it before I reached them so nobody could tell me I was late. Arrived late with dirt all over my face and nothing to show for it."],
      ["movement", "An awkward descent", "Climbed down headfirst to reach a fruit. A loose strand of vine dragged across my belly. Reached to pull it away, lost sight of the fruit, and found it again when my nose hit it."],
      ["feeding", "A fruit worth defending", "Dragged a fallen fruit away from the group. Bit through the skin and discovered most of it was rotten. Kept eating the good corner with my back turned, unwilling to surrender the argument."],
      ["weather", "The wet queue", "We sheltered along a branch during the shower. The one above shook herself first. I shook next. A great deal of rain reached the last coati without ever falling out of the sky."],
      ["social", "Borrowed vigilance", "The others stopped digging and looked up. I had my nose under a root. Left it there while I listened. Nobody called an alarm, so I finished. They were looking at me."],
      ["wonder", "A whole tree eating", "The fallen trunk crumbled beneath my claws. Ants scattered, beetles moved deeper, a pale grub curled away. I had thought the tree was finished. Spent so long investigating it that I became last again."],
      ["feeding", "Easy pickings", "A fruit fell while I searched the ground. Jumped sideways before it landed. Went back and ate it, grateful that my fear usually gives things enough time to stop moving."],
      ["social", "She came back", "Got behind the group at the rotten trunk. A familiar nose appeared beside mine. She took the grub I had exposed and left. I followed her, relieved and furious in roughly equal amounts."],
      ["movement", "The smell can wait", "Passed the good log while everyone was moving. Took three more steps before turning back. The smallest coati turned with me. Now there are two of us who will explain the delay badly."],
    ]),
  },
  {
    characterId: "bramble-shortlegs", identityNameBase: "Bramble Shortlegs", platform: "rss",
    bio: "A common wombat who dug a perfectly good home and is still arguing with the roots.",
    location: { name: "Cradle Mountain grassland edge", coordinates: { lat: -41.65, lng: 145.95 } },
    episodes: unbound("common wombat", [
      ["movement", "The root won tonight", "I widened the sleeping chamber toward the left. There was a root. Dug under it, found a thicker root, tried above it, and came through into my own entrance tunnel.\n\nSat with my nose sticking out of the hole I had made. Cool air on my face. A decent view of the grass.\n\nSlept in the old chamber. I will decide what the new hole is for when I am less tired."],
      ["feeding", "Very particular grass", "The grass beside my entrance had been stepped on until it tasted of dust. I walked past it to the fresh patch, grazed for a while, then found a fresher patch beyond that.\n\nBy dawn I was farther from home than I liked. Hurried back and ate the dusty grass outside my door before going in.\n\nIt tasted much better when I could lie down immediately afterward."],
      ["weather", "A small improvement", "Water ran into the new hole during the rain. I woke with one wet flank and blamed the root first, because we had already had a disagreement.\n\nPushed loose earth into the opening. The trickle stopped. More earth. No water. I lay down against the repaired wall and felt pleased with myself.\n\nWoke with one wet flank. Had blocked the water inside with me."],
      ["danger", "No further forward", "Something sniffed at the entrance while I was resting. I turned around and pressed my rump toward the sound. It stayed there breathing for a while. I stayed there being difficult to bite.\n\nEventually the breathing went away. I backed farther out to be certain and sat on a thistle.\n\nAfter all that excellent defense, a plant got the first real complaint out of me."],
      ["wonder", "The chamber smelled wrong", "The rain finally stopped. My sleeping place smelled of wet earth instead of me. I nosed along the walls, lay down, got up, and nosed along them again.\n\nBrought some dry grass inside. Settled on it. The stems poked my belly, but beneath them was the old worn dip I had made with years of sleeping.\n\nKicked the grass aside. Put my belly where it belonged."],
      ["social", "The doorway disagreement", "Another wombat was grazing outside my burrow when I came out. I grunted. She moved a little. I came farther out and grunted again.\n\nShe moved onto the fresh patch I had been saving. I followed to object, which left her perfectly free to walk past me and inspect my entrance.\n\nWe spent an unreasonable amount of evening moving each other off places neither of us was using."],
      ["movement", "The long way is open", "A branch fell across my usual route to the grass. Went around it for three nights. On the fourth, I shoved under it until bark scraped my back and the whole thing shifted.\n\nA clear path. At last.\n\nTonight I walked around it out of habit and arrived at the grass before I remembered I had done any work. The branch is enjoying a much better life since we stopped meeting."],
      ["feeding", "The mouthful I carried", "Pulled a long strip of grass loose and carried it toward shelter. The far end dragged. It caught on a twig. I tugged, lost my grip, and watched the bent grass spring away from my mouth.\n\nStood with my jaws still working.\n\nThere was grass beneath every foot. Ate that. Occasionally looked back at the difficult piece, which had become less food than an unfinished disagreement."],
      ["weather", "A dry place for once", "The next rain came after I had repaired the wall from outside. I stayed awake to listen for water. Heard it pattering on the entrance, felt the cool air, waited for the familiar wetness.\n\nNothing reached me.\n\nEventually went out to check that it was raining properly. It was. Came back soaked and lay awake wondering how long a successful repair takes to feel successful."],
      ["wonder", "The useful root", "Dug a shallow scrape beside the root tonight. Leaned my back against it to rest. It held me at a comfortable angle, exactly where the old wall had not.\n\nStayed there longer than I meant to.\n\nI still dislike the root. It prevented a much larger chamber, caused several evenings of digging, and now expects me to admit it makes a good backrest. I was asleep before I finished listing the objections."],
    ]),
  },
  {
    characterId: "kit-snowshoe", identityNameBase: "Kit Snowshoe", platform: "rss",
    bio: "An American pika with enough hay for winter and several reasons to fetch one more mouthful.",
    location: { name: "Rocky Mountain alpine talus", coordinates: { lat: 40.4, lng: -105.75 } },
    episodes: unbound("American pika", [
      ["feeding", "Too wide for the doorway", "Cut a beautiful mouthful of stems at the meadow edge. Carried them all the way to my haypile. The stems caught across the gap between the rocks.\n\nPushed harder. They bent. Backed out, dropped them, and took the bundle through in two loads.\n\nIt looked smaller afterward. I went out for more, having learned almost the wrong thing from the whole experience."],
      ["social", "The neighbor's mouthful", "My neighbor came home carrying something greener than anything in my pile. I watched where he went next, waited until he disappeared, and visited the same patch.\n\nThe leaves were tough. Gathered some anyway.\n\nHe watched me bringing them back. I held my head unusually high. We now both have a pile containing leaves I do not especially like, though only one of us knows why."],
      ["weather", "Drying weather", "Spread the new stems where the sun reached them. A cloud covered the slope. I moved the stems. The sun returned to the first place.\n\nI stood between the two piles with a leaf hanging from my mouth.\n\nLeft half in each place. Went to gather more. When I came back, the whole slope was sunny, which seemed like a personal waste of my earlier effort."],
      ["danger", "A small voice, far away", "Heard the alarm from beyond the rocks and dropped my mouthful. A hawk crossed the meadow where I had been standing. Stayed under cover until I could hear the ordinary little movements again.\n\nCame out to collect my stems. They had blown into a crack.\n\nSpent the next while pulling them out one at a time. Each stem was a small, green inconvenience I was still around to have."],
      ["feeding", "The buried favorite", "I knew there were tender leaves near the bottom of the pile. Had put them there myself, before all the sensible tough stems.\n\nDug down with my nose and dragged out a mouthful. The upper pile slid. I repaired it, found another good leaf underneath, and disturbed it again.\n\nBy the time I finished breakfast, my carefully built winter food looked as though somebody had searched it for precisely what I had eaten."],
      ["social", "He knows that call", "Called at my neighbor for getting too close to my hay. He paused, took a leaf from a plant outside my pile, and went home.\n\nI called again. He did not pause that time.\n\nSat on my lookout rock until my chest stopped feeling so full of him. Then collected the leaves from the plant he had chosen. If they were good enough to ignore me for, I wanted them inside."],
      ["weather", "White at the entrance", "The first snow covered my path before I had finished using it. I went out, found the meadow changed, and came back with almost nothing.\n\nInside, the hay smelled of the hot days when I had gathered it. I picked out a stem and recognized the tough end I had nearly left behind.\n\nAte it. Picked another. I had been very annoying all summer. I was beginning to appreciate me."],
      ["wonder", "The roof moved", "Heard a soft collapse above the rocks. Snow settled over the gap and the little patch of daylight vanished.\n\nI stood beneath it, listening. The wind became faint. My own chewing sounded very close when I began again.\n\nI had spent the summer trying to put enough meadow inside these rocks. Now the mountain had put a roof over it. I inspected the haypile for leaks anyway."],
      ["feeding", "Winter portion", "Pulled out a stem longer than I needed and started eating from the tip. Halfway along, I was full.\n\nSet the rest back in the pile. Took it out again because the cut end faced the wrong way. Put it down properly.\n\nIn the long quiet afterward I could hear my neighbor moving beyond the rock. I hoped he had enough to eat and briefly wondered whether his stems were arranged any better."],
      ["movement", "The first green mistake", "Meltwater opened the edge of my winter entrance. Outside was a tiny green shoot. I cut it, carried it in, and placed it on the haypile before I noticed what I had done.\n\nFresh food. Right there. I could eat it now.\n\nTook it back out into the sun and chewed slowly. Then went to look for another, because a very old part of me had already started worrying about next winter."],
    ]),
  },
  {
    characterId: "mallow-fold", identityNameBase: "Mallow Fold", platform: "rss",
    bio: "A ground pangolin who can close herself completely and is working on the timing of opening again.",
    location: { name: "Kruger savanna woodland", coordinates: { lat: -24.15, lng: 31.55 } },
    episodes: unbound("ground pangolin", [
      ["danger", "Safe, but facing inward", "A branch snapped behind me and I folded shut. Tail over face, scales outside, everything soft carefully elsewhere.\n\nNothing touched me. Waited longer. Uncurled just enough to smell the air, heard something move, and folded again.\n\nWhen I finally opened, an old dry branch lay across the path. I stepped over it with particular care. It had already taken a good portion of my evening."],
      ["feeding", "The wrong small hole", "Found ants entering a crack and worked my tongue into it. A little food, a little dirt, then nothing. Opened the crack with my claws and discovered a passage turning away where my tongue could not follow.\n\nDug beside it. The ants changed course.\n\nI stood over several excellent holes and very little supper. Followed one ant out of the mess. She knew considerably more about where we should go next."],
      ["movement", "Claws held clear", "Walked across the hard ground with my front claws tucked up. A small stone shifted beneath one hind foot. Put a forefoot down, steadied myself, lifted it again.\n\nNobody saw. I checked.\n\nThen I crossed the rest of the patch in that dignified, careful posture and immediately used the protected claws to tear apart a mound. They were being saved for something much less delicate than walking."],
      ["weather", "A dry place occupied", "Reached a burrow as the rain started. Sniffed at the entrance. Something old had lived there, but nothing fresh answered my nose.\n\nWent in. The floor was dry and smelled unfamiliar. Turned twice before settling, trying to find a shape that belonged to me.\n\nWoke when my own tail brushed my face. Folded shut in somebody else's empty bedroom. It took a while to feel welcome again."],
      ["wonder", "The mound repaired itself", "Returned to the place I had opened the night before. The hole was smaller. Tiny bodies worked along its edges, putting the wall back.\n\nI sniffed, scratched a little, watched the traffic change.\n\nLeft with food in my stomach and the same strange impression as before: I keep finding dinner inside a thing that does not want to remain broken. By tomorrow I will have to knock the wall down again."],
      ["social", "A nose at the edge", "Another pangolin came along while I was feeding. We stopped close enough to smell each other. She nosed the disturbed earth, then moved past my flank.\n\nI nearly folded. Did not.\n\nShe continued down the path. I stayed where I was, feeling exposed and oddly pleased about having remained the same shape throughout a meeting. Then an ant reached the soft part of my nose and I lost all composure."],
      ["feeding", "The bitter patch", "The first mouthful from the new nest tasted wrong. Tried a smaller one. Same wrongness.\n\nI had walked a long way and opened a hard piece of ground. Stood over it, wanting the work to have been worth doing.\n\nEventually left. Found a better nest nearby and ate there. On the way back I sniffed the first hole once more, as if the taste might have improved because I had been reasonable."],
      ["danger", "Already gone", "Heard heavy movement in the grass and closed myself. This time something sniffed me. Warm breath against the scales. A touch, then footsteps moving away.\n\nI stayed shut until the insects sounded ordinary again.\n\nWhen I opened, I was hungry and a little stiff. The grass was bent beside me. I sniffed the flattened place, then went around it. There was plenty of path I had not been breathed on in."],
      ["movement", "The familiar detour", "Came to the bent grass and took the long way around. A week had passed. The smell was gone. I went around anyway.\n\nFound an ant trail on the detour and followed it to a useful patch of earth.\n\nAte until I stopped shaking loose soil from my claws. Tomorrow I may take the same route for the ants. I would prefer that to taking it for the breath I remember."],
      ["wonder", "Opened before the crickets", "A dry pod fell nearby. I tucked my head, began to fold, then stopped. The pod lay open in the dust. Seeds beside it. Nothing coming toward me.\n\nI stayed out. Sniffed it. Nudged one seed with my nose.\n\nThe crickets had not even resumed when I walked on. Later, in the burrow, I curled up to sleep and found the shape much nicer when I had chosen it for being tired."],
    ]),
  },
  {
    characterId: "nessa-whisker", identityNameBase: "Nessa Whisker", platform: "rss",
    bio: "An Arctic fox who remembers where she put things, provided the entire ground has not changed overnight.",
    location: { name: "Svalbard tundra coast", coordinates: { lat: 78.15, lng: 15.25 } },
    episodes: unbound("Arctic fox", [
      ["feeding", "Under the right stone", "Buried a scrap beside a flat stone and covered it carefully. Walked away. Came back to cover it better.\n\nA gull watched from farther along the shore. I waited for it to look elsewhere before leaving. It waited too.\n\nDug the scrap up and ate it. Spent the walk home much less hungry and still annoyed that the gull had been involved in my decision."],
      ["movement", "The careful approach", "The gull stood beside my buried scrap with its back turned. I lowered myself and crept toward it. Soft feet. No sound. Close enough now to smell the fish on its feathers.\n\nIt stepped aside before I reached it. Flew to a higher rock.\n\nI dug where it had stood and found nothing. Dug where I had actually buried the scrap and found dinner. I had stalked a bird to a place I knew was wrong because it looked so sure."],
      ["weather", "A tail's worth of shelter", "The wind found the gap between my nose and my tail. Curled tighter. It found the gap again.\n\nTurned around in the hollow and tucked my nose beneath the thickest fur. Quiet at last. Warm breath coming back to me.\n\nSlept until a gust dropped snow from the lip of the hollow directly onto my head. There are nights when lying down is most of the work."],
      ["social", "The other end of the scrap", "Another fox found the piece of food at the same time I did. We each took an end. Pulling accomplished very little except bringing our faces closer.\n\nShe let go suddenly. I staggered backward with all of it and stood looking triumphant in a shallow hole.\n\nBy the time I climbed out, she had found a second piece. It looked easier to eat."],
      ["wonder", "White fur, dark stones", "My coat had begun coming loose in pale tufts. Rubbed against a rock and left a little of winter on its edge.\n\nUnderneath I was darker. The bare ground no longer made me look like something that had wandered into the wrong season.\n\nSat in a sunny patch and pulled at another loose tuft. It stuck to my lip. A great deal of looking appropriate involves looking ridiculous first."],
      ["feeding", "The egg stayed whole", "Carried an egg away from the nesting ground with my jaws held gently. Too gently, perhaps. Stopped twice to adjust it.\n\nFound a hiding place and lowered my head. The egg rolled into a narrow gap. I pawed at it, made the gap deeper, and finally brought it back out.\n\nCracked it open and ate. I had intended to save it for later, but later had become mostly digging."],
      ["weather", "The known hollow vanished", "A drift filled the hollow where I had slept through the last storm. I scratched at the place I knew was the entrance. Nothing opened.\n\nWent around the rock and found shelter on its other side. Curled down there, still irritated with the missing hollow.\n\nWhen the wind changed in the night, it passed over me. I slept through it and woke annoyed to have been improved upon by snow."],
      ["social", "I heard her eating", "The other fox was behind the rocks. I could hear her chewing. Followed the sound and found a small piece she had left beside her.\n\nTook it. She glanced at me and kept eating.\n\nI carried mine away before settling, but not very far. When she finished and moved on, I watched her disappear. Then I searched the place where she had been sitting, because I was touched, not full."],
      ["feeding", "A remembered mouthful", "Found an old cache under a crust of snow. The food smelled strong and familiar. I had put it there before the storm, before the hollow vanished, before I changed my coat.\n\nAte it crouched against the wind.\n\nFor a little while the fox who had been less hungry did something useful for the fox who was hungry now. I licked the empty place thoroughly. She could have left more."],
      ["movement", "A route with fewer arguments", "Came to the rock where I used to turn left. The old hollow was visible again, shallow and bare. I sniffed it, found nothing worth staying for, and went around to the newer shelter.\n\nSettled with my back against the stone. No searching, no scratching, no surprise.\n\nThen got up to bury a scrap nearby. A familiar gull was watching. This time I carried it behind the rock before changing my mind and eating it."],
    ]),
  },
  {
    characterId: "mira-mask", identityNameBase: "Mira Mask", platform: "rss",
    bio: "A raccoon who trusts her hands, distrusts the stream, and keeps going back to ask it questions.",
    location: { name: "Great Smoky Mountains stream forest", coordinates: { lat: 35.62, lng: -83.47 } },
    episodes: unbound("raccoon", [
      ["feeding", "What my hands knew", "Felt something firm beneath a stone and reached farther in. My fingers found an edge, then a leg, then nothing. Lifted the stone. Empty sand.\n\nLooked at my wet paws as if one of them had failed to pass along a useful detail.\n\nPut them back in. Found a small crayfish farther downstream and held it carefully. My mouth was much less interested in the investigation than my hands had been."],
      ["movement", "A branch with an opinion", "Climbed out along a branch toward a hanging fruit. The branch lowered itself until the fruit was still just beyond my reach, but the ground was very far away.\n\nBacked toward the trunk. The branch rose. Reached again. It lowered.\n\nSat at the fork for a while, looking at the fruit. Eventually climbed down and found one on the ground. It tasted of a much shorter story."],
      ["wonder", "An empty shell's possibilities", "Found a shell in the shallows. Turned it over with both paws. Smooth outside, ridged opening, a hollow place my finger could enter. Nothing edible.\n\nPut it down. Picked it up from the other side. Same shell, but my hands seemed to need the whole answer.\n\nA leaf floated past carrying a small insect. I missed it while establishing for the third time that the shell was empty."],
      ["social", "Your side of the log", "Another raccoon came toward me along the fallen trunk. I stopped. She stopped. We sniffed, each waiting for the other to discover a need to be elsewhere.\n\nShe moved onto a side branch and let me pass. I went by slowly, pretending the arrangement had been obvious.\n\nAt the far end I slipped into the shallow water. Heard her continue across the dry part without stopping."],
      ["weather", "The stream moved my stone", "The rain raised the water over the flat stone where I usually sat. I reached for it with one paw and felt only current.\n\nTried from farther upstream. Then from downstream. From downstream I could see the perfectly dry ledge I had just left in order to stand knee-deep in the problem.\n\nClimbed back onto it and shook my paws. The ledge will do until my stone returns. It is not as good. It has a raccoon dripping on it."],
      ["feeding", "Held too many things", "Found several fallen nuts beneath a tree. Gathered them close with my paws, then tried to pick up one while keeping the others from rolling away.\n\nA nut escaped. Reached for it and lost two more.\n\nFinally sat over the whole little collection and ate one at a time. A perfectly ordinary way to have dinner, once I had exhausted the less ordinary ones."],
      ["danger", "The hollow behind me", "Heard heavy steps on the bank while I was feeling under a root. Climbed before I looked. From the trunk I saw a bear nose along the water where I had been standing.\n\nWent higher. Found a hollow and put most of myself inside it.\n\nWaited until the steps moved away. Then stayed longer because the hollow was dry, snug, and apparently something I could have been sleeping in all along."],
      ["social", "A dry crossing offered", "The other raccoon reached the fallen trunk while I was halfway across. I remembered her stepping aside for me. Tried to do the same.\n\nThe side branch dipped under my weight and touched the water.\n\nShe passed while I held myself just above the stream with both back feet sliding. I climbed up after her, soaked below the waist. She had made that look much less generous than it was."],
      ["wonder", "Found by touch", "The water dropped and my flat stone reappeared, farther downstream. I stepped onto it. Same dip beneath my paw, same rough edge. Sat there a moment.\n\nThe bank looked different from this angle. A root I had never searched reached into the shallows.\n\nPut my hands under it and felt something move. Forgot about the stone immediately. It had traveled through a flood to remain something I sat on while thinking about dinner."],
      ["movement", "The hollow is occupied", "Went back to the tree where I had hidden from the bear. Climbed to the hollow and sniffed. It smelled of me.\n\nWorked my shoulders inside, turned, tucked my feet close. I could hear the stream below without having to put anything into it.\n\nA scraping noise came from the bark outside. I opened one eye, then the other. A beetle. Reached out and inspected it. Almost settled down. There is always one more thing to check."],
    ]),
  },
];
