export interface SampleCharacterEpisode {
  subject: string;
  mediaSha1: string;
  theme: "transformation" | "feeding" | "weather" | "danger" | "wonder" | "social" | "courtship" | "family" | "movement" | "cosmic";
  title: string;
  body: string;
}

export interface SampleCharacterArc {
  characterId: string;
  identityNameBase: string;
  bio: string;
  platform: "facebook" | "instagram" | "linkedin" | "rss" | "x";
  episodes: readonly SampleCharacterEpisode[];
}

export const SAMPLE_CHARACTER_ARCS: readonly SampleCharacterArc[] = [
  {
    characterId: "manny-tis",
    identityNameBase: "Manny Tis",
    platform: "instagram",
    bio: "A praying mantis with excellent posture, a complicated relationship with birds, and several recent reasons to distrust the sky.",
    episodes: [
      {
        subject: "praying mantis",
        mediaSha1: "c88ce5d5c8cd990996d841db9af09646ae2d47c7",
        theme: "transformation",
        title: "New skin, same nerve",
        body: "I stepped out of my old skin before dawn. For twelve minutes I was soft, pale, and unable to fight a raindrop. Then my wings hardened.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "d419335f51a0e926dbd6a7a49d0e5449b6790d0a",
        theme: "feeding",
        title: "Violence, and better lighting.",
        body: "A bee mistook stillness for indecision. We resolved the ambiguity over breakfast.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "e5f6a877347285e1ca1e38f040566752f1b90305",
        theme: "weather",
        title: "Rain has hands",
        body: "One drop struck the leaf hard enough to move my entire morning. I attacked the second drop. This improved nothing, but honor survived.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "5e6da761a344b8f0a359091ac1b995a6d5c4056e",
        theme: "danger",
        title: "The sky grew talons",
        body: "The leaf went dark. A bird's beak closed where my head had been, and I fell through three branches. Somewhere below the second branch I left my body. Every fly I had ever eaten was waiting. Then I hit a twig, came back, and blamed the bird.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "4bd31bee0500c333e4367a0bbacb3b24efce198c",
        theme: "danger",
        title: "Inventory after death",
        body: "I came to hanging by one hind leg. Antennae: two. Forelegs: both. Bird: furious. I climbed until the screaming moved elsewhere.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "2cb2762eb9cb6f68bcbe16287fb038170521aaed",
        theme: "feeding",
        title: "Moth at midnight",
        body: "A moth landed beside me and beat one wing against the leaf for nine minutes. I waited for silence. Hunger won.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "31e1e5639ab0477d2a2466941d5883f6dfe1a57f",
        theme: "courtship",
        title: "Honest relationship terms",
        body: "She is magnificent. She may also eat me. At last, romance without hidden fees.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "7e07c6b30b74a08ea83cbbb05e68d54da3adfe10",
        theme: "danger",
        title: "Dawn, reconsidered",
        body: "The bird returned at sunrise. I flattened beneath a leaf while it tore apart a grasshopper above me. One leg bounced past. I stayed where I was.",
      },
      {
        subject: "praying mantis",
        mediaSha1: "d67cc98af34b60d6e8b2e7aa586aa9e05de4d3fd",
        theme: "wonder",
        title: "The ant took the long way",
        body: "An ant walked around both my feet without looking up. I had been standing still for an hour. It remains the bravest thing I have seen all week.",
      },
    ],
  },
  {
    characterId: "frogbert-angler",
    identityNameBase: "Frogbert Angler",
    platform: "x",
    bio: "A frogfish who walks instead of swimming, fishes with its forehead, and regards subtlety as a rumor spread by faster animals.",
    episodes: [
      {
        subject: "frogfish underwater",
        mediaSha1: "ab98dabf54fe33be92581795707d73fd56b68176",
        theme: "feeding",
        title: "Furniture with intentions",
        body: "I spent the morning impersonating a sponge. A shrimp complimented the upholstery and vanished halfway through the sentence.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "d8db811f9a3957e75569f46ac91be3a8456373b0",
        theme: "feeding",
        title: "The forehead economy",
        body: "My lure performed one small dance. Lunch crossed the reef voluntarily.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "28f071a8ba9eb3e27a92f099918b66dabe6f8662",
        theme: "movement",
        title: "Walking fish weather",
        body: "The current was rude, so I walked home on my fins. Swimming past me, everyone looked busy and arrived at the same coral.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "01e2e869995438145c0354c19e554df0a82dffd3",
        theme: "social",
        title: "Camouflage breach",
        body: "A cleaner wrasse recognized me beneath the algae. We stared at each other until professional courtesy became blackmail.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "4fac2f792ffba0fc2240e5e6cb792decd3596f65",
        theme: "courtship",
        title: "Crush beside the sponge",
        body: "Someone lumpy settled three corals away and pretended not to notice me. I changed color twice, casually, over forty minutes.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "e710824197892596f5f929fb93529038436cc68d",
        theme: "feeding",
        title: "A mouthful of consequences",
        body: "I lunged at a fish larger than prudence. For one bright second we were both certain this was the other's mistake.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "17fe76cd81e2688f0ba67e0de0b378e32bdd8d1c",
        theme: "danger",
        title: "Crossing open sand",
        body: "There was no coral for six body lengths. I walked the whole distance dressed as nothing. The grouper noticed at five.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "791547f8fd744ca2c6c6406b352b1c12282d63f0",
        theme: "social",
        title: "Back to being furniture",
        body: "The grouper passed. I found a new sponge and did not move until sunset. Then a shrimp tried to clean me. I allowed it.",
      },
      {
        subject: "frogfish underwater",
        mediaSha1: "9663a30640ec7d977a6ce02a9a1b87b875f85365",
        theme: "feeding",
        title: "Hunting without the trick",
        body: "My lure snapped before breakfast. I had to walk after lunch and bite it without deception. The fish watched me coming and waited anyway.",
      },
    ],
  },
  {
    characterId: "nudi-branch-manager",
    identityNameBase: "Nudi Branch Manager",
    platform: "facebook",
    bio: "A shell-free nudibranch carrying stolen stinging cells, impossible colors, and no patience for creatures impressed by shells.",
    episodes: [
      {
        subject: "nudibranch underwater",
        mediaSha1: "132c45ae85dc04fbd3f381cd972135af36b1f7ea",
        theme: "social",
        title: "No shell, better posture",
        body: "Everyone asks where my shell went. I ask why they still drag theirs over every rock.",
      },
      {
        subject: "nudibranch underwater",
        mediaSha1: "999b6de9c270b6cf084e91d32519aab2f1b24366",
        theme: "feeding",
        title: "Borrowed weapons department",
        body: "I ate a hydroid and kept its stinging cells for later. The distinction between lunch and armory is mostly paperwork.",
      },
      {
        subject: "nudibranch underwater",
        mediaSha1: "f78edbd368573323bec2926ac2459c1cc009a6f6",
        theme: "danger",
        title: "Color as warning",
        body: "These colors do not mean come closer. They mean I survived the last creature who misunderstood the colors.",
      },
      {
        subject: "nudibranch underwater",
        mediaSha1: "a1bfc86887366dde276f85612da527a42f49d3a1",
        theme: "movement",
        title: "Current events",
        body: "The tide lifted me off the rock and carried me six body lengths backward. I crawled forward again. By noon the rock had moved less than I had.",
      },
      {
        subject: "nudibranch mating",
        mediaSha1: "129c619a92dfef320bf5e9fb98b05742b3e36a7b",
        theme: "courtship",
        title: "We both brought everything",
        body: "Each of us arrived with eggs and sperm. We circled once, lined up on the right, and traded both.",
      },
      {
        subject: "nudibranch underwater",
        mediaSha1: "6da2fa0f46144ea10d89649891e6e7aef2964355",
        theme: "danger",
        title: "Stolen fire",
        body: "A fish took one look at my colors and kept coming. I gave it one borrowed sting. It spat me out before the second.",
      },
      {
        subject: "nudibranch eggs",
        mediaSha1: "4e80c87a290b277ca8c9770557c51119552827c8",
        theme: "family",
        title: "Ribbon of futures",
        body: "I laid the eggs in a white spiral and left the current to read them. Parenthood, but with calligraphy.",
      },
      {
        subject: "nudibranch underwater",
        mediaSha1: "09361b603602c7aa91cf31ea3236aa39d049a4f6",
        theme: "danger",
        title: "Everything retracts",
        body: "A shadow crossed the sand. I pulled my gills in, flattened against the rock, and waited. When I opened again, lunch was still there.",
      },
      {
        subject: "nudibranch underwater",
        mediaSha1: "a86cab4596ddf0314085105b82709bbfd72017ca",
        theme: "transformation",
        title: "Everything leans",
        body: "The current pressed every frill flat against my back. I held to the rock until they rose again.",
      },
    ],
  },
  {
    characterId: "cygnus-shy",
    identityNameBase: "Cygnus Shy",
    platform: "instagram",
    bio: "A swan whose neck knows exactly what it is doing while the rest of the bird keeps discovering weather, gravity, and witnesses.",
    episodes: [
      {
        subject: "swan",
        mediaSha1: "a28cb915c46d2dcb4966227b7b34b475cc5cdfdc",
        theme: "social",
        title: "Head tucked, world off",
        body: "I tucked my head beneath one wing and slept through an entire argument among geese. When I woke, the bread was gone and the geese were still arguing.",
      },
      {
        subject: "swan",
        mediaSha1: "cd185b8e433a0179c4ffea8bd75db0ecd252c90c",
        theme: "movement",
        title: "Airborne, eventually",
        body: "I ran across half the lake before the water let go. A heron watched the entire takeoff and offered nothing.",
      },
      {
        subject: "swan",
        mediaSha1: "ce1ef641230b414aeb30ce82ce63b418334d53a9",
        theme: "courtship",
        title: "An accidental heart",
        body: "Our necks met in perfect symmetry. We both pretended the heart shape was a coincidence arranged by water.",
      },
      {
        subject: "swan",
        mediaSha1: "eb7c447489d5ac7dc20d38c1a658b843f933102e",
        theme: "danger",
        title: "Elegance gets territorial",
        body: "A stranger approached the nest. I became six feet of white feathers and ancient profanity.",
      },
      {
        subject: "swan",
        mediaSha1: "c73bd0646805fbbb12ecd768c90d88ac07194f6d",
        theme: "feeding",
        title: "The deep end",
        body: "I tipped forward for pondweed and left my entire rear half pointing at the sky. A duck stole the best piece while I was underwater.",
      },
      {
        subject: "swan",
        mediaSha1: "fd8a4385cec80d48c4d960c5c4e145b8ca5834ad",
        theme: "family",
        title: "Small gray weather",
        body: "The cygnets climbed onto my back and slept beneath my wings. Nine small feet kept slipping under the same feather. I did not sleep.",
      },
      {
        subject: "swan",
        mediaSha1: "a2a57edb7708d629231c15bc1ff5fa6af728f513",
        theme: "transformation",
        title: "One feather refuses",
        body: "I preened every feather down my left side. One near the tail kept rising. I turned in three circles and began again.",
      },
    ],
  },
  {
    characterId: "flora-mingo",
    identityNameBase: "Flora Mingo",
    platform: "linkedin",
    bio: "A flamingo made pink by shrimp, at home in salt water, mud, long flights, and very large crowds.",
    episodes: [
      {
        subject: "flamingo",
        mediaSha1: "edc8481461023dbcd11a9cdd43607db51b9a5e49",
        theme: "transformation",
        title: "Before the pink",
        body: "I began gray. The pink arrived one mouthful at a time. Adults kept checking as if I were late.",
      },
      {
        subject: "flamingo",
        mediaSha1: "edb5d781162da4eb272fea42020ce8a14e36ef59",
        theme: "courtship",
        title: "One bird in thousands",
        body: "I found them in the pink confusion because their head turn was half a beat late.",
      },
      {
        subject: "flamingo",
        mediaSha1: "d7db5d3f032ac43eb40c19d527e79ea12e4a6ac8",
        theme: "feeding",
        title: "Upside-down supper",
        body: "I filter lunch with my head inverted and my beak underwater. The posture is undignified. The shrimp are excellent.",
      },
      {
        subject: "flamingo",
        mediaSha1: "93e39136932440ef7d122a427808cf6d1b383dd1",
        theme: "weather",
        title: "Night on one leg",
        body: "The lake cooled after sunset. I tucked my head into my back, lifted one foot, and woke to a thousand neighbors facing the wrong direction.",
      },
    ],
  },
  {
    characterId: "nova-remains",
    identityNameBase: "Nova Remains",
    platform: "rss",
    bio: "A supernova remnant processing one spectacular death across millennia while its scattered elements begin entirely different lives.",
    episodes: [
      {
        subject: "supernova remnant NASA",
        mediaSha1: "315078d06ac86e674de56d66f859d89bc516295e",
        theme: "cosmic",
        title: "The long before",
        body: "I spent millions of years making heavier elements in the dark. Nobody applauded. Stars learn patience before drama.",
      },
      {
        subject: "supernova remnant NASA",
        mediaSha1: "308e74d35484433631fb5f786294a1ecb6d6ae36",
        theme: "cosmic",
        title: "Gravity wins inward",
        body: "My core collapsed in less time than this sentence. Every layer above it discovered the terrible efficiency of falling.",
      },
      {
        subject: "supernova remnant NASA",
        mediaSha1: "69e0ef67759def985b27811707ef2b9baae03ce6",
        theme: "cosmic",
        title: "Then, everything outward",
        body: "I exploded once. The light crossed galaxies before I finished understanding what had happened.",
      },
      {
        subject: "supernova remnant NASA",
        mediaSha1: "451c25be5d978d1393363812ca1ae2f31f2db618",
        theme: "cosmic",
        title: "Aftermath learns color",
        body: "My shock wave keeps teaching old gas new colors.",
      },
      {
        subject: "supernova remnant NASA",
        mediaSha1: "c03fc532fda31868f7f0269abd2fe2eaa4560fb9",
        theme: "cosmic",
        title: "Iron leaves home",
        body: "I scattered iron into space. Somewhere ahead, a world will put it in blood and call the pulse its own.",
      },
      {
        subject: "supernova remnant NASA",
        mediaSha1: "30d841ea8b83576cf6e622d4fd5f08987daf8807",
        theme: "cosmic",
        title: "No longer singular",
        body: "I used to be one star. Now I am dust, light, pressure, memory, and several futures refusing to share a border.",
      },
      {
        subject: "supernova remnant NASA",
        mediaSha1: "ba2a2537792822fe82dd11f8f9d8aab93e37f1e0",
        theme: "cosmic",
        title: "Dust crosses the front",
        body: "A grain of dust entered my shock wave cold and left stripped to atoms. It had been intact longer than your planet.",
      },
    ],
  },
] as const;
