export interface SampleCorpusPlace {
  id: string;
  name: string;
  coordinates: {
    lat: number;
    lng: number;
  };
}

export interface SampleCorpusMediaAsset {
  id: string;
  unsplashId: string;
  baseUrl: string;
  photographer: string;
  alt: string;
  category: "desert" | "forest" | "ocean" | "space" | "wildlife" | "mountain" | "weather";
  fieldNote: string;
  placeId?: string;
}

export const SAMPLE_CORPUS_PLACES: readonly SampleCorpusPlace[] = [
  { id: "death-valley", name: "Death Valley National Park", coordinates: { lat: 36.5054, lng: -117.0794 } },
  { id: "sossusvlei", name: "Sossusvlei, Namibia", coordinates: { lat: -24.7284, lng: 15.3418 } },
  { id: "lynn-canyon", name: "Lynn Canyon, British Columbia", coordinates: { lat: 49.342, lng: -123.018 } },
  { id: "tasmania", name: "Tasmania, Australia", coordinates: { lat: -42.0409, lng: 146.8087 } },
  { id: "bondi", name: "Bondi Beach, Australia", coordinates: { lat: -33.8915, lng: 151.2767 } },
  { id: "black-sand", name: "Black Sand Beach, Iceland", coordinates: { lat: 63.4043, lng: -19.0446 } },
  { id: "lewa", name: "Lewa Wildlife Conservancy, Kenya", coordinates: { lat: 0.1975, lng: 37.4483 } },
  { id: "serengeti", name: "Serengeti National Park, Tanzania", coordinates: { lat: -2.3333, lng: 34.8333 } },
  { id: "baffin", name: "Baffin Island, Nunavut", coordinates: { lat: 69.0, lng: -72.0 } },
  { id: "moraine-lake", name: "Moraine Lake, Alberta", coordinates: { lat: 51.3217, lng: -116.186 } },
  { id: "silver-lake", name: "Silver Lake, California", coordinates: { lat: 37.7769, lng: -119.1258 } },
  { id: "colorado-springs", name: "Colorado Springs, Colorado", coordinates: { lat: 38.8339, lng: -104.8214 } },
] as const;

export const SAMPLE_CORPUS_MEDIA: readonly SampleCorpusMediaAsset[] = [
  {
    id: "death-valley-folds",
    unsplashId: "MzJjabZWBRo",
    baseUrl: "https://images.unsplash.com/photo-1517767037021-c64e8b6c48cb",
    photographer: "Kai Vu",
    alt: "Layered sand dunes beneath a pale blue sky",
    category: "desert",
    placeId: "death-valley",
    fieldNote: "The dunes spent the night moving six inches east and still accomplished more than most planning committees.",
  },
  {
    id: "death-valley-ridge",
    unsplashId: "0ZryeOcmx5o",
    baseUrl: "https://images.unsplash.com/photo-1656870679469-156e3c955489",
    photographer: "Brian Wangenheim",
    alt: "Warm sand dunes folding into shadow",
    category: "desert",
    placeId: "death-valley",
    fieldNote: "Wind erased every footprint before lunch. The desert has excellent data-retention policies.",
  },
  {
    id: "dubai-horizon",
    unsplashId: "eLJ7ilJ_FRA",
    baseUrl: "https://images.unsplash.com/photo-1678729984335-bfaff3572cbe",
    photographer: "Benjamin DeYoung",
    alt: "A broad golden dune beneath a clear blue horizon",
    category: "desert",
    fieldNote: "Nothing here is in a hurry except the light, which has a hard stop at sunset.",
  },
  {
    id: "sahara-lines",
    unsplashId: "T4WBBTa2bHc",
    baseUrl: "https://images.unsplash.com/photo-1683138158840-b9988d9fe42e",
    photographer: "Marco D'Abramo",
    alt: "Fine wind-carved lines across a Sahara dune",
    category: "desert",
    fieldNote: "The Sahara released another flawless interface today. Zero buttons. Astonishing adoption.",
  },
  {
    id: "death-valley-light",
    unsplashId: "NiPTXfxkumc",
    baseUrl: "https://images.unsplash.com/photo-1600718211907-62d4c3f13aed",
    photographer: "Nick Rickert",
    alt: "Sunlit desert ridges fading into the distance",
    category: "desert",
    placeId: "death-valley",
    fieldNote: "Temperature update: the rocks have withdrawn their support for touching them.",
  },
  {
    id: "oman-monochrome",
    unsplashId: "aRGeZa4BeZQ",
    baseUrl: "https://images.unsplash.com/photo-1591201233759-60736c1b05e6",
    photographer: "ruedi häberli",
    alt: "Monochrome desert ridges receding into haze",
    category: "desert",
    fieldNote: "A landscape reduced to light, shadow, and the dawning suspicion that we packed too much.",
  },
  {
    id: "sahara-aerial",
    unsplashId: "pdzQ1cAdftk",
    baseUrl: "https://images.unsplash.com/photo-1543259406-78111f6bb1c4",
    photographer: "Wolfgang Hasselmann",
    alt: "Aerial view of sculpted Sahara dunes",
    category: "desert",
    fieldNote: "From above, the dunes resemble a topographic map drawn by someone with no respect for roads.",
  },
  {
    id: "white-sands",
    unsplashId: "PhiT_BhJmvM",
    baseUrl: "https://images.unsplash.com/photo-1765498067720-6ff6847f8f85",
    photographer: "Royce Fonseca",
    alt: "Soft white dunes beneath a pale sky",
    category: "desert",
    fieldNote: "White Sands at dawn, when even geology briefly appears to believe in minimalism.",
  },
  {
    id: "lynn-canyon-falls",
    unsplashId: "HC_NsvLvKAw",
    baseUrl: "https://images.unsplash.com/photo-1664849275192-503e4c864380",
    photographer: "Brayden Prato",
    alt: "A waterfall descending through a mossy green forest",
    category: "forest",
    placeId: "lynn-canyon",
    fieldNote: "The waterfall has been running continuously without a status page. Operations is furious.",
  },
  {
    id: "tasmanian-falls",
    unsplashId: "AcnTc22Q3yk",
    baseUrl: "https://images.unsplash.com/photo-1656802039231-94575a93b255",
    photographer: "Donovan Simpkin",
    alt: "A narrow waterfall inside a Tasmanian rainforest",
    category: "forest",
    placeId: "tasmania",
    fieldNote: "Tasmania grew an entire cathedral while nobody was looking. Ferns handled the architecture.",
  },
  {
    id: "forest-cascade",
    unsplashId: "aEXwRPt0mIA",
    baseUrl: "https://images.unsplash.com/photo-1598212635910-5a023d41c461",
    photographer: "Matteo Betto",
    alt: "A bright cascade surrounded by dense forest",
    category: "forest",
    fieldNote: "Water found the shortest path downhill and then made it unnecessarily beautiful.",
  },
  {
    id: "luang-prabang-falls",
    unsplashId: "dhbcpyJo4m8",
    baseUrl: "https://images.unsplash.com/photo-1593315921963-463bb27d91b9",
    photographer: "note thanun",
    alt: "Emerald waterfalls flowing through tropical forest",
    category: "forest",
    fieldNote: "The pool is this color naturally. Marketing has been asked to leave the premises.",
  },
  {
    id: "catawba-falls",
    unsplashId: "tePtZeHXOus",
    baseUrl: "https://images.unsplash.com/photo-1531698451051-18c97580aeb2",
    photographer: "Nicole King",
    alt: "Waterfalls threading between green trees",
    category: "forest",
    fieldNote: "Every exposed rock has been upholstered in moss. The forest remains committed to softness.",
  },
  {
    id: "silver-falls",
    unsplashId: "rLvHNNUdcDo",
    baseUrl: "https://images.unsplash.com/photo-1636257763258-a78982bd7ead",
    photographer: "Dan Meyers",
    alt: "A tall waterfall framed by an autumn forest",
    category: "forest",
    fieldNote: "Low water, high drama. The waterfall understands seasonal programming.",
  },
  {
    id: "quinault-rainforest",
    unsplashId: "yPKSufaXya8",
    baseUrl: "https://images.unsplash.com/photo-1742669004759-0744a37623c9",
    photographer: "Peter Robbins",
    alt: "A cascade crossing moss-covered rock in a rainforest",
    category: "forest",
    fieldNote: "Annual rainfall remains excessive, magnificent, and unwilling to accept feedback.",
  },
  {
    id: "vermont-falls",
    unsplashId: "tTGLTHz5dbc",
    baseUrl: "https://images.unsplash.com/photo-1667400909492-f4ed6d183369",
    photographer: "Ronan Furuta",
    alt: "A forest waterfall surrounded by autumn leaves",
    category: "forest",
    fieldNote: "Vermont has begun its annual attempt to make every other color palette look unserious.",
  },
  {
    id: "miami-deep-blue",
    unsplashId: "SGRKqRz77Sg",
    baseUrl: "https://images.unsplash.com/photo-1521245488535-7d14e2e27b0f",
    photographer: "Guzmán Barquín",
    alt: "Aerial view of deep blue ocean waves",
    category: "ocean",
    fieldNote: "The Atlantic submitted its revised blue. It is, regrettably, perfect.",
  },
  {
    id: "bondi-sunrise",
    unsplashId: "0QfKOLzyOlQ",
    baseUrl: "https://images.unsplash.com/photo-1598782201500-aba4136c1379",
    photographer: "Laura Barry",
    alt: "Aerial waves reaching Bondi Beach at sunrise",
    category: "ocean",
    placeId: "bondi",
    fieldNote: "Bondi before breakfast. The ocean has already completed several thousand repetitions.",
  },
  {
    id: "florida-seafoam",
    unsplashId: "wmG0H8VSXLQ",
    baseUrl: "https://images.unsplash.com/photo-1630460209363-f247267a828c",
    photographer: "Clayton Malquist",
    alt: "Purple and green ocean water curling into foam",
    category: "ocean",
    fieldNote: "The shoreline redrew itself again. Version control has become ceremonial.",
  },
  {
    id: "grey-ocean",
    unsplashId: "JoExVeViDZM",
    baseUrl: "https://images.unsplash.com/photo-1588586278060-f44a6b7d4f56",
    photographer: "Angus Gray",
    alt: "Silver ocean waves viewed from above",
    category: "ocean",
    fieldNote: "Today the sea declined color and concentrated entirely on texture.",
  },
  {
    id: "zeebrugge-tide",
    unsplashId: "jRPxlHqc_no",
    baseUrl: "https://images.unsplash.com/photo-1617701473939-a925b03f7e84",
    photographer: "Jonas Leupe",
    alt: "Aerial view of tide lines along a wide shore",
    category: "ocean",
    fieldNote: "The tide arrived precisely on schedule and refused all meeting invitations.",
  },
  {
    id: "yallingup-rocks",
    unsplashId: "YAKiohnJWek",
    baseUrl: "https://images.unsplash.com/photo-1605605999979-42a49c4ae1e8",
    photographer: "Mikolaj Felinski",
    alt: "Ocean waves breaking around dark coastal rocks",
    category: "ocean",
    fieldNote: "Rock versus ocean, year nine million. Neither side appears interested in mediation.",
  },
  {
    id: "iceland-black-beach",
    unsplashId: "oUTmhg97gzY",
    baseUrl: "https://images.unsplash.com/photo-1615390265246-72d3198a48b7",
    photographer: "Ása Steinarsdóttir",
    alt: "White waves crossing a black Icelandic beach",
    category: "ocean",
    placeId: "black-sand",
    fieldNote: "Iceland put the beach in dark mode and somehow improved the contrast ratio.",
  },
  {
    id: "nusa-penida-water",
    unsplashId: "CWbSS7qfEQc",
    baseUrl: "https://images.unsplash.com/photo-1590757879641-d23ccb04d98d",
    photographer: "Ryan Farid",
    alt: "Turquoise water breaking against the coast of Nusa Penida",
    category: "ocean",
    fieldNote: "The reef has deployed turquoise without consulting the design system.",
  },
  {
    id: "wizard-nebula",
    unsplashId: "jjLriBJqsno",
    baseUrl: "https://images.unsplash.com/photo-1761851399330-ad05101ded44",
    photographer: "Scott Lord",
    alt: "The Wizard Nebula glowing among dense stars",
    category: "space",
    fieldNote: "The Wizard Nebula is seventy light-years wide, proving subtlety was never a universal requirement.",
  },
  {
    id: "nature-fireworks",
    unsplashId: "eNoeWZkO7Zc",
    baseUrl: "https://images.unsplash.com/photo-1516331138075-f3adc1e149cd",
    photographer: "Alexander Andrews",
    alt: "A violet nebula shining against deep space",
    category: "space",
    fieldNote: "A stellar nursery containing several thousand newborn suns and no discernible bedtime policy.",
  },
  {
    id: "milky-way-field",
    unsplashId: "1IBvC4HWuAc",
    baseUrl: "https://images.unsplash.com/photo-1763793931094-69376e20a3bd",
    photographer: "Samuel Quek",
    alt: "The Milky Way crowded with stars and nebulae",
    category: "space",
    fieldNote: "The Milky Way contains at least one hundred billion stars and still found room for our emails.",
  },
  {
    id: "bubble-nebula",
    unsplashId: "rTZW4f02zY8",
    baseUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564",
    photographer: "NASA",
    alt: "Blue and violet gas surrounding the Bubble Nebula",
    category: "space",
    fieldNote: "A seven-light-year bubble blown by a star. The scale of cosmic showing off remains difficult to overstate.",
  },
  {
    id: "cosmic-clouds",
    unsplashId: "hw0fSU82dWc",
    baseUrl: "https://images.unsplash.com/photo-1767188789455-90e503ee3a4b",
    photographer: "Marek Pavlík",
    alt: "Colorful clouds of gas and stars in deep space",
    category: "space",
    fieldNote: "Interstellar dust, but make it cathedral lighting.",
  },
  {
    id: "blue-nebula",
    unsplashId: "BbYtd1lQiCE",
    baseUrl: "https://images.unsplash.com/photo-1770067139926-aec4f8eb9aa2",
    photographer: "Mathieu Coquerille",
    alt: "A dark blue nebula filled with bright stars",
    category: "space",
    fieldNote: "The universe has once again used blue more effectively than our entire species.",
  },
  {
    id: "orion-running-man",
    unsplashId: "W_g46NO0xzM",
    baseUrl: "https://images.unsplash.com/photo-1743710426934-89887ca897d8",
    photographer: "Scott Lord",
    alt: "Orion and the Running Man nebulae glowing red and violet",
    category: "space",
    fieldNote: "Orion is forming new stars while we debate whether the meeting needed an agenda.",
  },
  {
    id: "deep-space-c63",
    unsplashId: "bd4138UBIp8",
    baseUrl: "https://images.unsplash.com/photo-1762590322961-7a982c39e000",
    photographer: "thibault henry",
    alt: "A colorful nebula surrounded by a dense star field",
    category: "space",
    fieldNote: "C63, seen here refusing to be described as merely a cloud.",
  },
  {
    id: "forest-elephant",
    unsplashId: "9r31y3vI4HA",
    baseUrl: "https://images.unsplash.com/photo-1697613688115-bf49ecc5a56c",
    photographer: "Kyle Mills",
    alt: "An elephant standing quietly among forest vegetation",
    category: "wildlife",
    fieldNote: "The elephant entered without sound, which feels like an unreasonable feature for an animal this size.",
  },
  {
    id: "lewa-elephant",
    unsplashId: "nyvR6wbU1ho",
    baseUrl: "https://images.unsplash.com/photo-1535941339077-2dd1c7963098",
    photographer: "David Clode",
    alt: "A solitary elephant crossing golden grass at dawn",
    category: "wildlife",
    placeId: "lewa",
    fieldNote: "Dawn at Lewa. The elephant declined to hurry and was immediately promoted to management.",
  },
  {
    id: "elephant-family",
    unsplashId: "WPjbl0vZMrk",
    baseUrl: "https://images.unsplash.com/photo-1771341387722-01f4881541b0",
    photographer: "Marc Eggert",
    alt: "An elephant mother and calf sheltered by green forest",
    category: "wildlife",
    fieldNote: "The calf remains under close supervision after attempting to investigate absolutely everything.",
  },
  {
    id: "senegal-giraffe",
    unsplashId: "n66xjjQRLe8",
    baseUrl: "https://images.unsplash.com/photo-1777919344387-4d1bce4ebdba",
    photographer: "Francesca Fabian",
    alt: "A giraffe rising above a dry savanna woodland",
    category: "wildlife",
    fieldNote: "The giraffe has reviewed the canopy and would like everyone to know the leaves are excellent up here.",
  },
  {
    id: "chobe-giraffe",
    unsplashId: "gMW7Tspz2s4",
    baseUrl: "https://images.unsplash.com/photo-1759214636214-3f01d07dbe7b",
    photographer: "Ed Wingate",
    alt: "A giraffe standing in golden evening light",
    category: "wildlife",
    fieldNote: "Golden hour arrived. The giraffe was already dressed for it.",
  },
  {
    id: "open-ocean-whale",
    unsplashId: "atoq20n6FQI",
    baseUrl: "https://images.unsplash.com/photo-1761209620907-6cacb3426c61",
    photographer: "Hannah Reding",
    alt: "A whale exhaling across a bright open ocean",
    category: "wildlife",
    fieldNote: "A whale surfaced, took one breath, and improved the entire horizon.",
  },
  {
    id: "alaska-polar-bear",
    unsplashId: "CHqbiMhQ_wE",
    baseUrl: "https://images.unsplash.com/flagged/photo-1591475791029-f9efe6297456",
    photographer: "Hans-Jurgen Mager",
    alt: "A young polar bear walking across snow",
    category: "wildlife",
    placeId: "baffin",
    fieldNote: "The bear inspected the snowfield and found our presence aesthetically unnecessary.",
  },
  {
    id: "polar-bear-shore",
    unsplashId: "CuGwp9Bdtl4",
    baseUrl: "https://images.unsplash.com/photo-1710256441308-b28104d3e0ec",
    photographer: "Francesco Ungaro",
    alt: "A polar bear walking along a broad shoreline",
    category: "wildlife",
    fieldNote: "A polar bear on the shore, carrying no equipment and still better prepared than we are.",
  },
  {
    id: "moraine-lake",
    unsplashId: "DXQUIS4Tl9w",
    baseUrl: "https://images.unsplash.com/photo-1694125398686-fdbce8ca1054",
    photographer: "Ali Kazal",
    alt: "Moraine Lake surrounded by evergreen forest and mountains",
    category: "mountain",
    placeId: "moraine-lake",
    fieldNote: "Moraine Lake continues to look computationally expensive.",
  },
  {
    id: "chicago-lightning",
    unsplashId: "4ZM2GxzT6lI",
    baseUrl: "https://images.unsplash.com/photo-1783700111001-3e0452cd2052",
    photographer: "Ryan Heuer",
    alt: "Lightning descending from a dark summer storm",
    category: "weather",
    fieldNote: "The storm delivered one trillion watts without a charger, invoice, or venture round.",
  },
  {
    id: "colorado-lightning",
    unsplashId: "nbqlWhOVu6k",
    baseUrl: "https://images.unsplash.com/photo-1492011221367-f47e3ccd77a0",
    photographer: "David Moum",
    alt: "White lightning branching through purple storm clouds",
    category: "weather",
    placeId: "colorado-springs",
    fieldNote: "Colorado put on a light show with no concern for the venue's electrical limits.",
  },
  {
    id: "silver-lake-morning",
    unsplashId: "jAAk__SlP8U",
    baseUrl: "https://images.unsplash.com/photo-1624239364354-93ae3e590f66",
    photographer: "Simon Hurry",
    alt: "A calm mountain lake beneath a clear morning sky",
    category: "mountain",
    placeId: "silver-lake",
    fieldNote: "Silver Lake before the wind arrives and begins editing the reflections.",
  },
  {
    id: "peyto-lake-light",
    unsplashId: "Svnrlh3lXZ0",
    baseUrl: "https://images.unsplash.com/photo-1660162129606-c12ece87e967",
    photographer: "Mario Häfliger",
    alt: "Sun rays crossing a blue mountain lake and snowy peaks",
    category: "mountain",
    fieldNote: "The last sunlight reached the lake and briefly made every camera setting seem correct.",
  },
  {
    id: "trentino-dawn",
    unsplashId: "6tcvf72JOmg",
    baseUrl: "https://images.unsplash.com/photo-1783352404326-e2cfa1f88552",
    photographer: "Filippo Molinari",
    alt: "A tranquil alpine lake at dawn beneath distant peaks",
    category: "mountain",
    fieldNote: "The lake achieved perfect stillness. We immediately ruined it by discussing aperture.",
  },
  {
    id: "night-storm",
    unsplashId: "rjXQHinrMuI",
    baseUrl: "https://images.unsplash.com/photo-1786655012659-2516429015e0",
    photographer: "Dmytro Koplyk",
    alt: "Lightning illuminating dense clouds above dark water",
    category: "weather",
    fieldNote: "The atmosphere has escalated the disagreement.",
  },
  {
    id: "storm-bolt",
    unsplashId: "3sgw31LmGWQ",
    baseUrl: "https://images.unsplash.com/photo-1767273875341-34b29eec7d68",
    photographer: "Kyle Hinkson",
    alt: "A lightning bolt cutting through a black storm sky",
    category: "weather",
    fieldNote: "One bolt, several million volts, no visible onboarding flow.",
  },
] as const;

export const SAMPLE_CORPUS_VERSION = 1;

export function sampleCorpusPlace(placeId: string | undefined): SampleCorpusPlace | undefined {
  return placeId
    ? SAMPLE_CORPUS_PLACES.find((candidate) => candidate.id === placeId)
    : undefined;
}

export function sampleCorpusMedia(index: number): SampleCorpusMediaAsset {
  const normalized = ((index % SAMPLE_CORPUS_MEDIA.length) + SAMPLE_CORPUS_MEDIA.length) % SAMPLE_CORPUS_MEDIA.length;
  return SAMPLE_CORPUS_MEDIA[normalized]!;
}

export function sampleCorpusMediaUrl(
  asset: SampleCorpusMediaAsset,
  options: { width?: number; height?: number } = {},
): string {
  const width = options.width ?? 1_440;
  const height = options.height;
  const params = new URLSearchParams({
    auto: "format",
    fit: "crop",
    q: "82",
    w: width.toString(),
  });
  if (height) params.set("h", height.toString());
  return `${asset.baseUrl}?${params.toString()}`;
}

export function sampleCorpusUnsplashUrl(asset: SampleCorpusMediaAsset): string {
  return `https://unsplash.com/photos/${asset.unsplashId}?utm_source=freed&utm_medium=referral`;
}
