import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import {
  chmodSync,
  mkdtempSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  listPromotionBranchDiffFiles,
  listPromotionDiffFiles,
} from "./release-promotion-shared.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const VALIDATE_RELEASE_PROMOTION = path.join(
  __dirname,
  "validate-release-promotion.mjs",
);
const VALIDATE_MAIN_PR = path.join(__dirname, "validate-main-pr.mjs");
const VALIDATE_MAIN_BACKFLOW = path.join(
  __dirname,
  "validate-main-backflow.mjs",
);

function git(cwd, args) {
  return execFileSync("git", args, {
    cwd,
    encoding: "utf8",
  }).trim();
}

function writeRepoFile(cwd, relativePath, contents) {
  const filePath = path.join(cwd, relativePath);
  mkdirSync(path.dirname(filePath), { recursive: true });
  writeFileSync(filePath, contents);
}

function cargoLockContents(
  rootVersion,
  {
    dependencyVersion = "1.0.0",
    dependencySource = "registry+https://github.com/rust-lang/crates.io-index",
    dependencyChecksum = "a".repeat(64),
    injectDependency = false,
  } = {},
) {
  const injectedPackage = injectDependency
    ? `\n[[package]]\nname = "injected-dependency"\nversion = "7.7.7"\nsource = "registry+https://attacker.invalid/index"\nchecksum = "${"c".repeat(64)}"\n`
    : "";
  const injectedRootDependency = injectDependency
    ? ' "injected-dependency",\n'
    : "";

  return `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "fixture-dependency"\nversion = "${dependencyVersion}"\nsource = "${dependencySource}"\nchecksum = "${dependencyChecksum}"\n${injectedPackage}\n[[package]]\nname = "freed-desktop"\nversion = "${rootVersion}"\ndependencies = [\n "fixture-dependency",\n${injectedRootDependency}]\n`;
}

function writeCargoLock(cwd, rootVersion, options) {
  writeRepoFile(
    cwd,
    "packages/desktop/src-tauri/Cargo.lock",
    cargoLockContents(rootVersion, options),
  );
}

function maliciousCargoLockOptions() {
  return {
    dependencyVersion: "9.9.9",
    dependencySource: "registry+https://attacker.invalid/index",
    dependencyChecksum: "b".repeat(64),
    injectDependency: true,
  };
}

function commitAll(cwd, message) {
  git(cwd, ["add", "."]);
  git(cwd, ["commit", "-m", message]);
}

function updateOriginRef(cwd, branchName, refName = branchName) {
  const sha = git(cwd, ["rev-parse", refName]);
  git(cwd, ["update-ref", `refs/remotes/origin/${branchName}`, sha]);
}

function makeTempRepo() {
  const cwd = mkdtempSync(path.join(tmpdir(), "freed-release-promotion-"));
  git(cwd, ["init", "-b", "main"]);
  git(cwd, ["config", "user.name", "Codex Test"]);
  git(cwd, ["config", "user.email", "codex@example.com"]);

  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main';\n",
  );
  writeRepoFile(
    cwd,
    "packages/pwa/package.json",
    '{\n  "name": "@freed/pwa",\n  "version": "0.0.0"\n}\n',
  );
  writeRepoFile(
    cwd,
    "packages/desktop/package.json",
    '{\n  "name": "@freed/desktop",\n  "version": "0.0.0"\n}\n',
  );
  writeRepoFile(
    cwd,
    "packages/desktop/src-tauri/Cargo.toml",
    '[package]\nname = "freed-desktop"\nversion = "0.0.0"\n',
  );
  writeCargoLock(cwd, "0.0.0");
  writeRepoFile(
    cwd,
    "packages/desktop/src-tauri/tauri.conf.json",
    '{\n  "version": "0.0.0"\n}\n',
  );
  writeRepoFile(cwd, "scripts/release.sh", "#!/usr/bin/env bash\n");
  writeRepoFile(cwd, "docs/PHASE-1-FOUNDATION.md", "# Phase 1\n");
  writeRepoFile(cwd, "website/next.config.ts", "export default {};\n");
  writeRepoFile(
    cwd,
    "release-notes/releases/v0.0.0.json",
    '{\n  "approved": true\n}\n',
  );
  commitAll(cwd, "initial");

  git(cwd, ["branch", "dev"]);
  updateOriginRef(cwd, "main");
  updateOriginRef(cwd, "dev");
  return cwd;
}

function runNode(scriptPath, args) {
  return spawnSync(process.execPath, [scriptPath, ...args], {
    encoding: "utf8",
  });
}

test("listPromotionDiffFiles ignores release-only metadata drift", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev';\n",
  );
  writeRepoFile(
    cwd,
    "packages/pwa/package.json",
    '{\n  "name": "@freed/pwa",\n  "version": "26.4.2100"\n}\n',
  );
  writeCargoLock(cwd, "26.4.2100");
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": true\n}\n',
  );
  commitAll(cwd, "dev change");

  const files = listPromotionDiffFiles({
    fromRef: "dev",
    toRef: "main",
    cwd,
  });

  assert.deepEqual(files, ["packages/pwa/src/app.ts"]);
});

test("validate-release-promotion fails when main is stale on product files", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev';\n",
  );
  commitAll(cwd, "dev change");

  const result = runNode(VALIDATE_RELEASE_PROMOTION, [
    `--cwd=${cwd}`,
    "--from-ref=dev",
    "--to-ref=main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Production release blocked/);
  assert.match(result.stderr, /packages\/pwa\/src\/app\.ts/);
});

test("validate-main-backflow ignores squashed promotion content already in dev history", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'promoted';\n",
  );
  commitAll(cwd, "dev feature");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "main"]);
  git(cwd, ["merge", "--squash", "--no-commit", "dev"]);
  git(cwd, ["commit", "-m", "chore: promote dev into main"]);
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'next dev change';\n",
  );
  commitAll(cwd, "next dev change");
  updateOriginRef(cwd, "dev");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow fails when main has product content absent from dev", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main hotfix';\n",
  );
  commitAll(cwd, "main hotfix");
  updateOriginRef(cwd, "main");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /packages\/pwa\/src\/app\.ts/);
});

test("validate-main-backflow ignores files that exist only on dev", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/dev-only.ts",
    "export const ready = true;\n",
  );
  commitAll(cwd, "feat: dev-only file");
  updateOriginRef(cwd, "dev");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow accepts a shared file when dev is a strict textual superset", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main';\nexport const hotfix = true;\n",
  );
  commitAll(cwd, "fix: main hotfix");
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main';\nexport const hotfix = true;\nexport const nextDevChange = true;\n",
  );
  commitAll(cwd, "feat: extend the shared file on dev");
  updateOriginRef(cwd, "dev");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow rejects mode drift when dev also adds text", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));
  const scriptPath = "scripts/shared-tool.sh";

  git(cwd, ["checkout", "main"]);
  writeRepoFile(cwd, scriptPath, "#!/usr/bin/env bash\nprintf 'main\\n'\n");
  chmodSync(path.join(cwd, scriptPath), 0o755);
  commitAll(cwd, "fix: add executable main tool");
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    scriptPath,
    "#!/usr/bin/env bash\nprintf 'main\\n'\nprintf 'dev\\n'\n",
  );
  chmodSync(path.join(cwd, scriptPath), 0o644);
  commitAll(cwd, "feat: extend shared tool without executable mode");
  updateOriginRef(cwd, "dev");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /scripts\/shared-tool\.sh/);
});

test("validate-main-backflow rejects a shared file when dev changes a main line and adds content", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main hotfix';\nexport const shared = true;\n",
  );
  commitAll(cwd, "fix: main hotfix");
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'changed on dev';\nexport const shared = true;\nexport const nextDevChange = true;\n",
  );
  commitAll(cwd, "feat: change and extend the shared file on dev");
  updateOriginRef(cwd, "dev");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /packages\/pwa\/src\/app\.ts/);
});

test("validate-main-backflow rejects binary differences", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  writeRepoFile(cwd, "packages/pwa/src/app.ts", Buffer.from([0, 1, 2, 3]));
  commitAll(cwd, "fix: main binary state");
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(cwd, "packages/pwa/src/app.ts", Buffer.from([0, 1, 2, 3, 4]));
  commitAll(cwd, "feat: dev binary state");
  updateOriginRef(cwd, "dev");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /packages\/pwa\/src\/app\.ts/);
});

test("validate-main-backflow rejects a main-side file deletion missing from dev", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  rmSync(path.join(cwd, "packages/pwa/src/app.ts"));
  commitAll(cwd, "fix: remove broken app entry on main");
  updateOriginRef(cwd, "main");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /packages\/pwa\/src\/app\.ts/);
});

test("validate-main-backflow accepts a promoted deletion after dev re-adds the file", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  rmSync(path.join(cwd, "packages/pwa/src/app.ts"));
  commitAll(cwd, "fix: remove obsolete app entry");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "main"]);
  git(cwd, ["merge", "--squash", "dev"]);
  git(cwd, ["commit", "-m", "chore: promote dev into main"]);
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'new dev entry';\n",
  );
  commitAll(cwd, "feat: add replacement app entry");
  updateOriginRef(cwd, "dev");
  assert.equal(
    spawnSync(
      "git",
      ["merge-base", "--is-ancestor", "origin/main", "origin/dev"],
      { cwd },
    ).status,
    1,
  );

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow accepts a reverse-integrated deletion after dev re-adds the file", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  rmSync(path.join(cwd, "packages/pwa/src/app.ts"));
  commitAll(cwd, "fix: remove broken app entry on main");
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  rmSync(path.join(cwd, "packages/pwa/src/app.ts"));
  commitAll(cwd, "chore: merge main back into dev after v26.7.700 (#929)");
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'new dev entry';\n",
  );
  commitAll(cwd, "feat: add replacement app entry");
  updateOriginRef(cwd, "dev");
  assert.equal(
    spawnSync(
      "git",
      ["merge-base", "--is-ancestor", "origin/main", "origin/dev"],
      { cwd },
    ).status,
    1,
  );

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow rejects a main rollback to an older dev blob", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'promoted';\n",
  );
  commitAll(cwd, "feat: promoted state");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "main"]);
  git(cwd, ["merge", "--squash", "dev"]);
  git(cwd, ["commit", "-m", "chore: promote dev into main"]);

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'next dev state';\n",
  );
  commitAll(cwd, "feat: next dev state");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main';\n",
  );
  commitAll(cwd, "fix: roll back app state on main");
  updateOriginRef(cwd, "main");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /packages\/pwa\/src\/app\.ts/);
});

test("validate-main-backflow accepts a reverse-integrated main hotfix after dev advances", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev state';\n",
  );
  commitAll(cwd, "feat: dev state");

  git(cwd, ["checkout", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'main hotfix';\n",
  );
  commitAll(cwd, "fix: main hotfix");
  updateOriginRef(cwd, "main");

  git(cwd, ["checkout", "dev"]);
  git(cwd, ["checkout", "main", "--", "packages/pwa/src/app.ts"]);
  commitAll(cwd, "chore: merge main back into dev after v26.7.700 (#929)");
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'next dev state';\n",
  );
  commitAll(cwd, "feat: next dev state");
  updateOriginRef(cwd, "dev");
  assert.equal(
    spawnSync(
      "git",
      ["merge-base", "--is-ancestor", "origin/main", "origin/dev"],
      { cwd },
    ).status,
    1,
  );

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow ignores release-only main metadata", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": true\n}\n',
  );
  writeRepoFile(
    cwd,
    "packages/pwa/package.json",
    '{\n  "name": "@freed/pwa",\n  "version": "26.4.2100"\n}\n',
  );
  writeCargoLock(cwd, "26.4.2100");
  commitAll(cwd, "release metadata");
  updateOriginRef(cwd, "main");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Main backflow is in sync/);
});

test("validate-main-backflow rejects dependency drift in Cargo.lock", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "main"]);
  writeCargoLock(cwd, "26.4.2100", maliciousCargoLockOptions());
  commitAll(cwd, "release metadata with dependency drift");
  updateOriginRef(cwd, "main");

  const result = runNode(VALIDATE_MAIN_BACKFLOW, [
    `--cwd=${cwd}`,
    "--dev-ref=origin/dev",
    "--main-ref=origin/main",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Dev refresh needed/);
  assert.match(result.stderr, /packages\/desktop\/src-tauri\/Cargo\.lock/);
});

test("validate-main-pr passes for a fresh promotion branch", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev';\n",
  );
  writeRepoFile(
    cwd,
    "packages/desktop/src-tauri/Cargo.toml",
    '[package]\nname = "freed"\nversion = "26.4.2100"\n',
  );
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": false\n}\n',
  );
  commitAll(cwd, "dev change");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "-b", "chore/promote-dev-to-main-20260421", "main"]);
  git(cwd, ["merge", "--squash", "--no-commit", "dev"]);
  git(cwd, [
    "commit",
    "-m",
    "chore: promote dev into main for production release",
  ]);

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=chore/promote-dev-to-main-20260421",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Promotion branch matches origin\/dev/);
});

test("validate-main-pr rejects third-content release metadata on a promotion branch", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev';\n",
  );
  writeRepoFile(
    cwd,
    "packages/desktop/src-tauri/Cargo.toml",
    '[package]\nname = "freed"\nversion = "26.4.2100"\n',
  );
  commitAll(cwd, "dev change");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "-b", "chore/promote-dev-to-main-20260421", "main"]);
  git(cwd, ["merge", "--squash", "--no-commit", "dev"]);
  git(cwd, [
    "commit",
    "-m",
    "chore: promote dev into main for production release",
  ]);
  writeRepoFile(
    cwd,
    "packages/desktop/src-tauri/Cargo.toml",
    '[package]\nname = "freed"\nversion = "26.4.2100"\n\n[dependencies]\nunreviewed = "1"\n',
  );
  commitAll(cwd, "chore: inject release-only drift");

  assert.deepEqual(
    listPromotionBranchDiffFiles({
      fromRef: "origin/dev",
      toRef: "HEAD",
      cwd,
    }),
    ["packages/desktop/src-tauri/Cargo.toml"],
  );

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=chore/promote-dev-to-main-20260421",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Promotion PR is stale/);
  assert.match(result.stderr, /packages\/desktop\/src-tauri\/Cargo\.toml/);
});

test("validate-main-pr rejects third-content release notes on a promotion branch", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev';\n",
  );
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": false\n}\n',
  );
  commitAll(cwd, "dev change");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "-b", "chore/promote-dev-to-main-20260421", "main"]);
  git(cwd, ["merge", "--squash", "--no-commit", "dev"]);
  git(cwd, [
    "commit",
    "-m",
    "chore: promote dev into main for production release",
  ]);
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": true\n}\n',
  );
  commitAll(cwd, "chore: inject release-note drift");

  assert.deepEqual(
    listPromotionBranchDiffFiles({
      fromRef: "origin/dev",
      toRef: "HEAD",
      cwd,
    }),
    ["release-notes/releases/v26.4.2100.json"],
  );

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=chore/promote-dev-to-main-20260421",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /Promotion PR is stale/);
  assert.match(result.stderr, /release-notes\/releases\/v26\.4\.2100\.json/);
});

test("validate-main-pr allows website build config in promotion branches", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "dev"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'dev';\n",
  );
  writeRepoFile(
    cwd,
    "website/next.config.ts",
    "export default { transpilePackages: ['@freed/shared'] };\n",
  );
  commitAll(cwd, "dev build config");
  updateOriginRef(cwd, "dev");

  git(cwd, ["checkout", "-b", "chore/promote-dev-to-main-20260421", "main"]);
  git(cwd, ["merge", "--squash", "--no-commit", "dev"]);
  git(cwd, [
    "commit",
    "-m",
    "chore: promote dev into main for production release",
  ]);

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=chore/promote-dev-to-main-20260421",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Promotion branch matches origin\/dev/);
});

test("validate-main-pr rejects product changes on a non-promotion branch", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "-b", "fix/manual-main-edit", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/src/app.ts",
    "export const value = 'oops';\n",
  );
  commitAll(cwd, "manual main edit");

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=fix/manual-main-edit",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /must come from a promotion branch/);
});

test("validate-main-pr allows release-only metadata updates on a release branch", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "-b", "chore/release-v26.4.2100", "main"]);
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": true\n}\n',
  );
  writeRepoFile(
    cwd,
    "packages/pwa/package.json",
    '{\n  "name": "@freed/pwa",\n  "version": "26.4.2100"\n}\n',
  );
  writeCargoLock(cwd, "26.4.2100");
  commitAll(cwd, "release metadata");

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=chore/release-v26.4.2100",
  ]);

  assert.equal(result.status, 0);
  assert.match(result.stdout, /Release-only metadata update detected/);
});

test("validate-main-pr rejects dependency drift in a release lockfile", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "-b", "chore/release-v26.4.2100", "main"]);
  writeRepoFile(
    cwd,
    "packages/pwa/package.json",
    '{\n  "name": "@freed/pwa",\n  "version": "26.4.2100"\n}\n',
  );
  writeCargoLock(cwd, "26.4.2100", maliciousCargoLockOptions());
  commitAll(cwd, "release metadata with dependency drift");

  assert.deepEqual(
    listPromotionDiffFiles({
      fromRef: "origin/main",
      toRef: "HEAD",
      cwd,
    }),
    ["packages/desktop/src-tauri/Cargo.lock"],
  );

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=chore/release-v26.4.2100",
  ]);

  assert.equal(result.status, 1);
  assert.match(result.stderr, /must come from a promotion branch/);
});

test("validate-main-pr rejects release-only metadata on a non-release branch", (t) => {
  const cwd = makeTempRepo();
  t.after(() => rmSync(cwd, { recursive: true, force: true }));

  git(cwd, ["checkout", "-b", "docs/release-note-sync", "main"]);
  writeRepoFile(
    cwd,
    "release-notes/releases/v26.4.2100.json",
    '{\n  "approved": true\n}\n',
  );
  commitAll(cwd, "release metadata");

  const result = runNode(VALIDATE_MAIN_PR, [
    `--cwd=${cwd}`,
    "--base-ref=origin/main",
    "--head-ref=HEAD",
    "--head-branch=docs/release-note-sync",
  ]);

  assert.equal(result.status, 1);
  assert.match(
    result.stderr,
    /must come from a branch named chore\/release-\*/,
  );
});
