/* This file is generated by scripts/generate-library-core-contract.mjs. */

export const LIBRARY_CORE_SQLITE_CONTRACT_VERSION = 1 as const;
export const LIBRARY_CORE_SQLITE_SCHEMA_VERSION = 1 as const;
export const LIBRARY_CORE_SQLITE_PROTOCOL_VERSION = 2 as const;
export const LIBRARY_CORE_NORMALIZED_CHECKPOINT_FORMAT = "freed_normalized_checkpoint_v2" as const;
export const LIBRARY_CORE_CHECKPOINT_RECORD_MAXIMUM_CANONICAL_BYTES = 131072 as const;
export const LIBRARY_CORE_CHECKPOINT_PAGE_MAXIMUM_DECODED_BYTES = 2097152 as const;
export const LIBRARY_CORE_CHECKPOINT_PAGE_MAXIMUM_RECORDS = 128 as const;
export const LIBRARY_CORE_NATIVE_EXPORT_MAXIMUM_RESPONSE_BYTES = 1048576 as const;
export const LIBRARY_CORE_CONTENT_CHUNK_BYTES = 65536 as const;

export const LIBRARY_CORE_CHECKPOINT_RECORD_REGISTRY = [
  {
    registryKey: "00_checkpoint_header",
    primaryKey: "singleton",
    payload: "checkpoint_header"
  },
  {
    registryKey: "10_feed_item",
    primaryKey: "text",
    payload: "feed_item"
  },
  {
    registryKey: "20_rss_feed",
    primaryKey: "text",
    payload: "rss_feed"
  },
  {
    registryKey: "30_person",
    primaryKey: "text",
    payload: "person"
  },
  {
    registryKey: "40_account",
    primaryKey: "text",
    payload: "account"
  },
  {
    registryKey: "50_preference",
    primaryKey: "text",
    payload: "preference"
  },
  {
    registryKey: "60_relationship",
    primaryKey: "relationship",
    payload: "relationship"
  },
  {
    registryKey: "70_field_clock",
    primaryKey: "field",
    payload: "field_clock"
  },
  {
    registryKey: "80_tombstone",
    primaryKey: "entity",
    payload: "tombstone"
  },
  {
    registryKey: "90_actor_state",
    primaryKey: "text",
    payload: "actor_state"
  },
  {
    registryKey: "a0_receipt",
    primaryKey: "receipt",
    payload: "receipt"
  },
  {
    registryKey: "b0_blob_descriptor",
    primaryKey: "digest",
    payload: "blob_descriptor"
  },
  {
    registryKey: "b1_content_chunk",
    primaryKey: "chunk",
    payload: "content_chunk"
  }
] as const;
export type LibraryCoreCheckpointRegistryEntry = (typeof LIBRARY_CORE_CHECKPOINT_RECORD_REGISTRY)[number];
export type LibraryCoreCheckpointRegistryKey = LibraryCoreCheckpointRegistryEntry["registryKey"];
export type LibraryCoreCheckpointPayloadKind = LibraryCoreCheckpointRegistryEntry["payload"];
export type LibraryCoreCheckpointPrimaryKeyCodec = LibraryCoreCheckpointRegistryEntry["primaryKey"];

export const LIBRARY_CORE_OPERATION_IDS = [
  "account_person_assignment",
  "account_remove",
  "account_restore",
  "account_upsert",
  "feed_item_archive_assignment",
  "feed_item_capture_upsert",
  "feed_item_like_assignment",
  "feed_item_like_sync_receipt",
  "feed_item_read_assignment",
  "feed_item_remove",
  "feed_item_restore",
  "feed_item_saved_assignment",
  "feed_item_seen_sync_receipt",
  "feed_items_archive_frozen",
  "feed_items_archive_read_unsaved_frozen",
  "feed_items_content_signals_backfill_frozen",
  "feed_items_deduplicate_frozen",
  "feed_items_delete_archived_frozen",
  "feed_items_prune_archived_frozen",
  "feed_items_read_frozen",
  "feed_items_unarchive_saved_frozen",
  "person_reach_out_append",
  "person_remove_and_accounts",
  "person_remove_detach_accounts",
  "person_restore",
  "person_upsert",
  "preferences_leaf_assignment",
  "provider_capture_snapshot_reconcile",
  "provider_intent",
  "rss_feed_remove_keep_items",
  "rss_feed_remove_with_items",
  "rss_feed_restore",
  "rss_feed_title_assignment",
  "rss_feed_upsert",
  "rss_feeds_heal_untitled_frozen",
  "rss_feeds_remove_keep_items",
  "rss_feeds_remove_with_items",
  "sample_library_import",
  "sample_library_remove",
] as const;
export type LibraryCoreOperationId = (typeof LIBRARY_CORE_OPERATION_IDS)[number];

export const LIBRARY_CORE_QUERY_IDS = [
  "account_detail_v1",
  "background_item_page_v1",
  "change_feed_v1",
  "content_fetch_claim_v1",
  "export_enumeration_v1",
  "feed_browse_page_v1",
  "feed_browse_page_v2",
  "feed_browse_page_v3",
  "feed_facets_v1",
  "feed_page_v1",
  "feed_subscription_page_v1",
  "item_detail_v1",
  "item_reader_body_v1",
  "library_facet_summary_v1",
  "library_surface_items_v1",
  "map_markers_v1",
  "person_detail_v1",
  "person_timeline_v1",
  "persons_graph_v1",
  "preferences_snapshot_v1",
  "provider_action_claim_v1",
  "provider_media_page_v1",
  "repair_work_claim_v1",
  "saved_analytics_v1",
  "saved_feed_page_v1",
  "search_page_v1",
  "semantic_classification_claim_v1",
  "story_wall_candidates_v1",
] as const;
export type LibraryCoreQueryId = (typeof LIBRARY_CORE_QUERY_IDS)[number];
