export const SOFT_VIEWPORT_MASK_SIZE_PX = 20;
export const SOFT_VIEWPORT_RADIUS_PX = 20;

export const DEFAULT_PRIMARY_SIDEBAR_WIDTH_PX = 256;
export const MAX_PRIMARY_SIDEBAR_WIDTH_PX = 400;
export const PRIMARY_SIDEBAR_GAP_WIDTH_PX = 16;
export const AUXILIARY_DRAWER_GAP_WIDTH_PX = 12;
export const FRIENDS_SIDEBAR_GAP_WIDTH_PX = 12;
export const TOOLBAR_SIDEBAR_SLOT_PADDING_RIGHT_PX = 8;
export const TOOLBAR_ICON_BUTTON_SIZE_PX = 40;
export const TOOLBAR_BOUNDARY_BUTTON_GAP_PX = 8;

export const COMPACT_PRIMARY_SIDEBAR_WIDTH_PX = 48;
export const COMPACT_RAIL_OUTER_INSET_PX = 4;
export const CLOSED_PRIMARY_SIDEBAR_SNAP_THRESHOLD_PX = 40;
export const COMPACT_PRIMARY_SIDEBAR_SNAP_THRESHOLD_PX = 184;
export const NARROW_LABELED_SIDEBAR_THRESHOLD_PX = 200;
export const EXPANDED_SIDEBAR_PADDING_CROSSOVER_WIDTH_PX = 220;
export const EXPANDED_SIDEBAR_ROOMY_PADDING_PX = 16;
export const EXPANDED_SIDEBAR_CONDENSED_PADDING_PX = 8;

export function px(value: number): string {
  return `${value}px`;
}
